import { Building2, Car, MoreHorizontal, Plus, ReceiptText } from "lucide-react"
import { useState } from "react"
import { calculateVehicleCost } from "../../domain/calculations"
import type { CashDocument } from "../../domain/model"
import { CostDialog, SiteDialog, VehicleDialog } from "@/components/EntityDialogs"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardAction, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { dateIt, eur, formatNumber } from "@/lib/format"
import type { AppState } from "../state"
import type { DeleteTarget } from "../types"

type Editor = { kind: "cost" | "vehicle" | "site"; id?: string } | null

export function ResourcesView({ doc, appState, requestDelete }: { doc: CashDocument; appState: AppState; requestDelete: (target: DeleteTarget) => void }) {
  const [editor, setEditor] = useState<Editor>(null)
  const [vehicleCostPreviews, setVehicleCostPreviews] = useState<Record<string, { costPerKm: string; referenceDate: string }>>({})
  const otherSites = doc.sites.filter((site) => !site.client)
  const annualCosts = doc.businessCosts.reduce((sum, cost) => sum + Number(cost.monthlyAmount) * 12, 0).toFixed(2)
  const checkVehicleCost = async (id: string) => { const vehicle = doc.vehicles.find((entry) => entry.id === id); if (!vehicle || !doc.settings.fuelTerritory) { appState.setError({ code: "MISSING_DATA", message: "Configura il territorio MIMIT." }); return } const fuel = await window.cash.mimit.latestFuelPrice({ territory: doc.settings.fuelTerritory, fuel: vehicle.fuel }); if (!fuel.ok) { appState.setError(fuel.error); return } const result = calculateVehicleCost(vehicle, fuel.value); if (!result.ok) { appState.setError(result.error); return } setVehicleCostPreviews((current) => ({ ...current, [id]: { costPerKm: result.value.costPerKm, referenceDate: fuel.value.referenceDate } })) }
  const toggleVehicleDefault = (id: string) => appState.mutate((document) => { document.settings.defaultVehicleId = document.settings.defaultVehicleId === id ? undefined : id })
  const toggleSiteDefault = (id: string) => appState.mutate((document) => { document.settings.defaultDepartureSiteId = document.settings.defaultDepartureSiteId === id ? undefined : id })
  return <><Tabs defaultValue="costs" className="space-y-4"><TabsList><TabsTrigger value="costs"><ReceiptText />Costi aziendali</TabsTrigger><TabsTrigger value="vehicles"><Car />Veicoli</TabsTrigger><TabsTrigger value="sites"><Building2 />Altre sedi</TabsTrigger></TabsList>
    <TabsContent value="costs"><Card><CardHeader><div><CardTitle>Costi aziendali</CardTitle><CardDescription>Totale annuale: <strong>{eur(annualCosts)}</strong>.</CardDescription></div><CardAction><Button onClick={() => setEditor({ kind: "cost" })}><Plus />Nuovo costo</Button></CardAction></CardHeader><CardContent>{doc.businessCosts.length ? <Table><TableHeader><TableRow><TableHead>Categoria</TableHead><TableHead>Descrizione</TableHead><TableHead>Mensile</TableHead><TableHead /></TableRow></TableHeader><TableBody>{doc.businessCosts.map((cost) => <TableRow key={cost.id}><TableCell><Badge variant="secondary">{cost.category}</Badge></TableCell><TableCell>{cost.description}</TableCell><TableCell>{eur(cost.monthlyAmount)}</TableCell><TableCell><RowMenu label={cost.description} onEdit={() => setEditor({ kind: "cost", id: cost.id })} onDelete={() => requestDelete({ kind: "cost", id: cost.id, label: cost.description })} /></TableCell></TableRow>)}</TableBody></Table> : <Empty title="Nessun costo aziendale" onAction={() => setEditor({ kind: "cost" })} />}</CardContent></Card></TabsContent>
    <TabsContent value="vehicles"><Card><CardHeader><div><CardTitle>Veicoli</CardTitle><CardDescription>Il predefinito viene proposto soltanto nelle nuove Trasferte.</CardDescription></div><CardAction><Button onClick={() => setEditor({ kind: "vehicle" })}><Plus />Nuovo veicolo</Button></CardAction></CardHeader><CardContent className="space-y-4"><Alert><AlertTitle>Evita duplicazioni</AlertTitle><AlertDescription>Assicurazione, bollo e manutenzione non vanno duplicati nei costi aziendali.</AlertDescription></Alert>{doc.vehicles.length ? <Table><TableHeader><TableRow><TableHead>Veicolo</TableHead><TableHead>Consumo</TableHead><TableHead>Costo/km</TableHead><TableHead /></TableRow></TableHeader><TableBody>{doc.vehicles.map((vehicle) => { const preview = vehicleCostPreviews[vehicle.id]; return <TableRow key={vehicle.id}><TableCell><span className="font-medium">{vehicle.name}</span>{doc.settings.defaultVehicleId === vehicle.id ? <Badge className="ml-2" variant="outline">Predefinito</Badge> : null}</TableCell><TableCell>{formatNumber(vehicle.consumption, 2)} {vehicle.consumptionUnit}</TableCell><TableCell>{preview ? <>{preview.costPerKm} €/km <span className="text-xs text-muted-foreground">MIMIT {dateIt(preview.referenceDate)}</span></> : <Button size="sm" variant="outline" onClick={() => void checkVehicleCost(vehicle.id)}>Verifica ora</Button>}</TableCell><TableCell><RowMenu label={vehicle.name} onEdit={() => setEditor({ kind: "vehicle", id: vehicle.id })} onDefault={() => toggleVehicleDefault(vehicle.id)} defaultLabel={doc.settings.defaultVehicleId === vehicle.id ? "Rimuovi predefinito" : "Imposta come predefinito"} onDelete={() => requestDelete({ kind: "vehicle", id: vehicle.id, label: vehicle.name })} /></TableCell></TableRow> })}</TableBody></Table> : <Empty title="Nessun veicolo" onAction={() => setEditor({ kind: "vehicle" })} />}</CardContent></Card></TabsContent>
    <TabsContent value="sites"><Card><CardHeader><div><CardTitle>Altre sedi</CardTitle><CardDescription>Luoghi indipendenti, inclusa l’eventuale partenza globale.</CardDescription></div><CardAction><Button onClick={() => setEditor({ kind: "site" })}><Plus />Nuova sede</Button></CardAction></CardHeader><CardContent>{otherSites.length ? <Table><TableHeader><TableRow><TableHead>Nome</TableHead><TableHead>Indirizzo</TableHead><TableHead>Coordinate</TableHead><TableHead /></TableRow></TableHeader><TableBody>{otherSites.map((site) => <TableRow key={site.id}><TableCell><span className="font-medium">{site.name}</span>{doc.settings.defaultDepartureSiteId === site.id ? <Badge className="ml-2" variant="outline">Partenza predefinita</Badge> : null}</TableCell><TableCell>{site.address ?? "Non indicato"}</TableCell><TableCell>{site.location ? `${site.location.coordinates.longitude}, ${site.location.coordinates.latitude}` : "Da localizzare"}</TableCell><TableCell><RowMenu label={site.name} onEdit={() => setEditor({ kind: "site", id: site.id })} onDefault={() => toggleSiteDefault(site.id)} defaultLabel={doc.settings.defaultDepartureSiteId === site.id ? "Rimuovi partenza predefinita" : "Imposta come partenza predefinita"} onDelete={() => requestDelete({ kind: "site", id: site.id, label: site.name })} /></TableCell></TableRow>)}</TableBody></Table> : <Empty title="Nessuna altra sede" onAction={() => setEditor({ kind: "site" })} />}</CardContent></Card></TabsContent>
  </Tabs><CostDialog open={editor?.kind === "cost"} onOpenChange={(open) => { if (!open) setEditor(null) }} appState={appState} cost={editor?.kind === "cost" ? doc.businessCosts.find((entry) => entry.id === editor.id) : undefined} /><VehicleDialog open={editor?.kind === "vehicle"} onOpenChange={(open) => { if (!open) setEditor(null) }} appState={appState} vehicle={editor?.kind === "vehicle" ? doc.vehicles.find((entry) => entry.id === editor.id) : undefined} /><SiteDialog open={editor?.kind === "site"} onOpenChange={(open) => { if (!open) setEditor(null) }} appState={appState} doc={doc} site={editor?.kind === "site" ? doc.sites.find((entry) => entry.id === editor.id) : undefined} /></>
}

function RowMenu({ label, onEdit, onDelete, onDefault, defaultLabel }: { label: string; onEdit: () => void; onDelete: () => void; onDefault?: () => void; defaultLabel?: string }) { return <DropdownMenu><DropdownMenuTrigger render={<Button variant="ghost" size="icon-sm" aria-label={`Azioni per ${label}`} />}><MoreHorizontal /></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={onEdit}>Modifica</DropdownMenuItem>{onDefault ? <DropdownMenuItem onClick={onDefault}>{defaultLabel}</DropdownMenuItem> : null}<DropdownMenuItem variant="destructive" onClick={onDelete}>Elimina</DropdownMenuItem></DropdownMenuContent></DropdownMenu> }
function Empty({ title, onAction }: { title: string; onAction: () => void }) { return <div className="grid min-h-40 place-items-center rounded-lg border border-dashed text-center"><div><p>{title}</p><Button className="mt-3" size="sm" onClick={onAction}><Plus />Aggiungi</Button></div></div> }
