import { describe,expect,it,vi } from 'vitest';
import { parseMimitCsv } from '../../src/native/integrations/mimit';
import { parseFoiSdmxCsv,revalueFromSeries } from '../../src/native/integrations/foi';
import { exportQuote, listCompanies, listConsultingProducts, searchClients, verifyActivation } from '../../src/native/integrations/fatture-in-cloud';
import { officialFetch } from '../../src/native/integrations/http';

describe('fonti ufficiali',()=>{
  it('blocca endpoint non allowlistati prima della rete',async()=>{const fetcher=vi.fn();const result=await officialFetch('https://example.com/dati',{},fetcher as unknown as typeof fetch);expect(result.ok).toBe(false);expect(fetcher).not.toHaveBeenCalled();});
  it('normalizza il CSV regionale MIMIT esatto',()=>{const csv='Aggiornamento 07-09-2026\nREGIONE;TIPOLOGIA;EROGAZIONE;PREZZO MEDIO\nLazio;Benzina;SELF;1.900\n';const result=parseMimitCsv(csv,'Lazio','Benzina','2026-09-08T00:00:00.000Z');expect(result.ok&&result.value.referenceDate).toBe('2026-09-07');expect(result.ok&&result.value.price).toBe('1.900');});
  it('rifiuta combinazioni non disponibili senza fallback',()=>{const csv='Aggiornamento 07-09-2026\nREGIONE;TIPOLOGIA;EROGAZIONE;PREZZO MEDIO\nLazio;Benzina;SELF;1.900\n';const result=parseMimitCsv(csv,'Lazio','GPL');expect(result.ok).toBe(false);});
  it('calcola FOI solo da osservazioni valide e confrontabili',()=>{const parsed=parseFoiSdmxCsv('TIME_PERIOD,OBS_VALUE,BASE_PER\n2024-01,100.0,2015=100\n2026-07,110.0,2015=100');expect(parsed.ok).toBe(true);if(!parsed.ok)return;const result=revalueFromSeries('100.00','2024-01',parsed.value,'2026-09-08T00:00:00.000Z');expect(result.ok&&result.value.revaluedAmount).toBe('110.00');});
  it('filtra FOI generale senza tabacchi, scarta provvisori e applica il raccordo 1,214',()=>{const csv='E_COICOP_REV_ISTAT,TIME_PERIOD,OBS_VALUE,OBS_STATUS,BASE_PER\n00,2025-12,999,,2015=100\n00ST,2025-12,122.6,,2015=100\n00ST,2026-01,100.4,,2025=100\n00ST,2026-02,101.0,P,2025=100';const parsed=parseFoiSdmxCsv(csv);expect(parsed.ok).toBe(true);if(!parsed.ok)return;expect(parsed.value).toHaveLength(2);const result=revalueFromSeries('100.00','2025-12',parsed.value);expect(result.ok&&result.value.toPeriod).toBe('2026-01');expect(result.ok&&result.value.toLinkFactor).toBe('1.214');});
  it('verifica token, aziende e prodotto Consulenza sugli endpoint ufficiali',async()=>{const fetcher=vi.fn(async(input:string|URL|Request)=>{const url=String(input);if(url.endsWith('/user/companies'))return new Response(JSON.stringify({data:{companies:[{id:1,name:'Studio'}]}}),{status:200});if(url.includes('/company/info'))return new Response(JSON.stringify({data:{id:1,name:'Studio',access_info:{permissions:{fic_clients:'read',fic_products:'read',fic_issued_documents_detailed:{quotes:'write'}}}}}),{status:200});if(url.includes('/products/2'))return new Response(JSON.stringify({data:{id:2,name:'Consulenza',default_vat:{id:3,value:0,description:'Forfettario'}}}),{status:200});return new Response(JSON.stringify({data:[{id:2,name:'Consulenza'}]}),{status:200});}) as unknown as typeof fetch;const companies=await listCompanies('token',fetcher);expect(companies.ok&&companies.value[0]?.name).toBe('Studio');const products=await listConsultingProducts('token','1',fetcher);expect(products.ok&&products.value).toEqual([{id:'2',name:'Consulenza'}]);expect((await verifyActivation('token','1','2',fetcher)).ok).toBe(true);expect(vi.mocked(fetcher).mock.calls.every(call=>String(call[0]).startsWith('https://api-v2.fattureincloud.it/'))).toBe(true);});
  it('rifiuta permessi insufficienti e marca snapshot remoti',async()=>{const denied=vi.fn(async()=>new Response(JSON.stringify({data:{id:1,name:'Studio',access_info:{permissions:{fic_clients:'read',fic_products:'none',fic_issued_documents_detailed:{quotes:'read'}}}}}),{status:200})) as unknown as typeof fetch;expect((await verifyActivation('token','1','2',denied)).ok).toBe(false);const clientsFetch=vi.fn(async()=>new Response(JSON.stringify({data:[{id:9,name:'Cliente',vat_number:'12345678901'}]}),{status:200})) as unknown as typeof fetch;const clients=await searchClients('1','cli','token',clientsFetch);expect(clients.ok&&clients.value[0]?.source).toBe('fatture_in_cloud');});
  it('invia una sola richiesta con prodotto Consulenza, descrizione modificabile, quantità 1 e IVA corrente',async()=>{const fetcher=vi.fn(async()=>new Response(JSON.stringify({data:{id:77}}),{status:200})) as unknown as typeof fetch;const result=await exportQuote({companyId:'1',clientId:'9',productId:'2',product:{id:'2',name:'Consulenza',vat:{id:'3',value:0}},lines:[{itemIds:['44c36ddb-75c1-4f6e-b13f-c778b29ce6bb'],description:'Analisi e installazione',amount:'125.50',quantity:1}],attemptId:'tentativo-1'},'token',fetcher);expect(result.ok&&result.value.outcome).toBe('success');expect(fetcher).toHaveBeenCalledTimes(1);const init=vi.mocked(fetcher).mock.calls[0]?.[1] as RequestInit;const payload=JSON.parse(String(init.body));expect(payload.data.items_list).toEqual([{product_id:2,name:'Consulenza',description:'Analisi e installazione',qty:1,net_price:125.5,vat:{id:3}}]);expect(payload.data.items).toBeUndefined();});
});
