import { mkdtemp, readdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { describe, expect, it } from 'vitest';
import { createEmptyDocument, createFiscalPreset2026 } from '../../src/domain/model';
import { backupPathFor, createArchive, migrateArchive, openArchive, previewMigration, restoreBackup, saveArchive } from '../../src/native/persistence';

describe('persistenza atomica',()=>{
  it('crea, incrementa, mantiene backup e blocca conflitto hash',async()=>{const dir=await mkdtemp(join(tmpdir(),'cash-'));const path=join(dir,'Cash.data.json');const created=await createArchive(path,createEmptyDocument('2026-09-08T00:00:00.000Z'));expect(created.ok).toBe(true);if(!created.ok)return;expect(created.value.token.revision).toBe(1);const doc=structuredClone(created.value.document!);doc.settings.fuelTerritory='Lazio';const saved=await saveArchive(path,doc,created.value.token);expect(saved.ok).toBe(true);expect(JSON.parse(await readFile(backupPathFor(path),'utf8')).revision).toBe(1);if(!saved.ok)return;const bytes=await readFile(path,'utf8');await writeFile(path,bytes.replace('"Lazio"','"Lazio "'));const conflict=await saveArchive(path,saved.value.document!,saved.value.token);expect(conflict.ok).toBe(false);if(!conflict.ok)expect(conflict.error.code).toBe('CONFLICT');});
  it('apre uno schema più nuovo in sola lettura',async()=>{const dir=await mkdtemp(join(tmpdir(),'cash-'));const path=join(dir,'future.json');const doc=createEmptyDocument();await writeFile(path,JSON.stringify({...doc,schemaVersion:99}));const opened=await openArchive(path);expect(opened.ok&&opened.value.readOnly).toBe(true);});
  it('migra schema 1 esplicitamente con backup e FIC disattivato',async()=>{const dir=await mkdtemp(join(tmpdir(),'cash-'));const path=join(dir,'legacy.json');const current=createEmptyDocument('2026-09-08T00:00:00.000Z');const profile=createFiscalPreset2026();profile.confirmed=true;const fiscal={...profile.fiscal} as Record<string,unknown>;fiscal.substituteTaxRate=fiscal.ordinarySubstituteTaxRate;for(const key of ['activityPhase','reducedEligibilityConfirmed','ordinaryApplicabilityConfirmed','reducedSubstituteTaxRate','ordinarySubstituteTaxRate'])delete fiscal[key];const legacy={...current,schemaVersion:1,settings:{fuelTerritory:'Lazio',ficCompanyId:'10',ficConsultingProductId:'20'},profiles:[{...profile,fiscal}],sites:[],quotes:[]} as Record<string,unknown>;delete legacy.localClients;await writeFile(path,JSON.stringify(legacy));const opened=await openArchive(path);expect(!opened.ok&&opened.error.code).toBe('MIGRATION_REQUIRED');expect((await previewMigration(path)).ok).toBe(true);const migrated=await migrateArchive(path);expect(migrated.ok).toBe(true);if(!migrated.ok)return;expect(migrated.value.document?.schemaVersion).toBe(2);expect(migrated.value.document?.settings.fic).toEqual({enabled:false,legacyReferences:{companyId:'10',productId:'20'}});expect(migrated.value.document?.profiles[0]?.confirmed).toBe(false);expect(JSON.parse(await readFile(backupPathFor(path),'utf8')).schemaVersion).toBe(1);});
  it('ripristina il backup solo esplicitamente, conserva entrambe le copie e assegna una nuova identità',async()=>{const dir=await mkdtemp(join(tmpdir(),'cash-'));const path=join(dir,'Cash.data.json');const created=await createArchive(path,createEmptyDocument('2026-09-08T00:00:00.000Z'));if(!created.ok)throw new Error(created.error.message);const changed=structuredClone(created.value.document!);changed.settings.fuelTerritory='Lazio';const saved=await saveArchive(path,changed,created.value.token);if(!saved.ok)throw new Error(saved.error.message);const restored=await restoreBackup(path,saved.value.token);expect(restored.ok).toBe(true);if(!restored.ok)return;expect(restored.value.document?.documentId).not.toBe(created.value.document?.documentId);expect(restored.value.document?.revision).toBe(1);expect(restored.value.document?.settings.fuelTerritory).toBeUndefined();const files=await readdir(dir);expect(files.some(name=>name.includes('.prima-ripristino.'))).toBe(true);expect(files.some(name=>name.includes('.backup-conservato.'))).toBe(true);});
});
