import { describe, expect, it } from 'vitest';
import { cloneReusableSubItem, cloneTemplate, reusableFromQuoteSubItem, templateFromQuote } from '../../src/domain/catalog';
import { meta, type ReusableSubItem, type Template } from '../../src/domain/model';

describe('copie indipendenti',()=>{
  it('rinnova tutte le identità senza propagare modifiche',()=>{const sub:ReusableSubItem={...meta(),kind:'time',description:'Gestione',minutes:30};const copy=cloneReusableSubItem(sub);copy.description='Altro';expect(copy.id).not.toBe(sub.id);expect(sub.description).toBe('Gestione');});
  it('rinnova template, voci, gruppi, opzioni e default',()=>{const option={...meta(),name:'Sì',subItems:[]};const group={...meta(),name:'Firmware',options:[option],defaultOptionId:option.id};const source:Template={...meta(),name:'Server',items:[{...meta(),name:'Config',subItems:[],variantGroups:[group]}]};const copy=cloneTemplate(source);expect(copy.id).not.toBe(source.id);expect(copy.items[0]!.variantGroups[0]!.defaultOptionId).toBe(copy.items[0]!.variantGroups[0]!.options[0]!.id);});
  it('salva sottovoci e template come copie senza dati automatici di viaggio',()=>{const option={...meta(),name:'Sì',subItems:[]};const group={...meta(),name:'G',options:[option],defaultOptionId:option.id};const travel={...meta(),kind:'travel' as const,description:'Viaggio',site:{sourceId:meta().id,name:'S',address:'A',oneWayKm:'10.0'},vehicleId:meta().id,roundTrip:true,occurrences:2,timeMode:'automatic' as const,totalMinutes:40,totalDistanceKm:'40.0',vehicleCostPerKm:'0.5',totalCost:'20.00',fuelEvidence:{fuel:'Benzina' as const,mode:'SELF' as const,territory:'Lazio',network:'NON_AUTOSTRADALE' as const,price:'1.800',priceUnit:'EUR/l' as const,referenceDate:'2026-09-08',acquiredAt:'2026-09-08T00:00:00.000Z'}};const reusable=reusableFromQuoteSubItem(travel);expect('site' in reusable).toBe(false);const source={...meta(),name:'Voce',subItems:[travel],variantGroups:[group],variantSelections:[]};const built=templateFromQuote('T',[source]);expect(built.ok).toBe(true);if(!built.ok)return;expect(built.value.items[0]?.id).not.toBe(source.id);expect(built.value.items[0]?.variantGroups[0]?.id).not.toBe(group.id);});
  it('riporta nell’opzione corretta le modifiche manuali generate dalla variante',()=>{const option={...meta(),name:'Completa',subItems:[{kind:'time' as const,description:'Originale',minutes:30}]};const group={...meta(),name:'Servizio',options:[option],defaultOptionId:option.id};const source={...meta(),name:'Voce',variantGroups:[group],variantSelections:[{groupId:group.id,optionId:option.id}],subItems:[{...meta(),kind:'time' as const,description:'Personalizzata',minutes:45,variantOwner:{groupId:group.id,optionId:option.id,definitionIndex:0},manuallyModified:true}]};const built=templateFromQuote('Personalizzato',[source]);expect(built.ok).toBe(true);if(!built.ok)return;expect(built.value.items[0]?.variantGroups[0]?.options[0]?.subItems[0]).toEqual({kind:'time',description:'Personalizzata',minutes:45});});
});
