import { describe, expect, it } from 'vitest';
import { calculateItem } from '../../src/domain/calculations';
import { applyVariantSelections, changeVariant } from '../../src/domain/variants';
import { meta, type QuoteItem } from '../../src/domain/model';

describe('varianti',()=>{
  it('somma gruppi e sostituisce soltanto il proprietario',()=>{const a1={...meta(),name:'No',subItems:[]};const a2={...meta(),name:'Sì',subItems:[{kind:'time' as const,description:'Firmware',minutes:30}]};const b={...meta(),name:'Media',subItems:[{kind:'time' as const,description:'RAID',minutes:30}]};const ga={...meta(),name:'Firmware',options:[a1,a2],defaultOptionId:a1.id};const gb={...meta(),name:'RAID',options:[b],defaultOptionId:b.id};const item:QuoteItem={...meta(),name:'Server',subItems:[{...meta(),kind:'time',description:'Base',minutes:60}],variantGroups:[ga,gb],variantSelections:[]};const applied=applyVariantSelections(item,{[ga.id]:a2.id,[gb.id]:b.id},{materializeTravel:()=>{throw new Error('unused')}});expect(applied.ok&&applied.value.subItems).toHaveLength(3);if(!applied.ok)return;const changed=changeVariant(applied.value,ga.id,a1.id,true,{materializeTravel:()=>{throw new Error('unused')}});expect(changed.ok&&changed.value.subItems.map(x=>x.description)).toEqual(['Base','RAID']);});
  it('richiede conferma se una sottovoce generata è modificata',()=>{const option={...meta(),name:'A',subItems:[]};const group={...meta(),name:'G',options:[option],defaultOptionId:option.id};const item:QuoteItem={...meta(),name:'X',variantGroups:[group],variantSelections:[],subItems:[{...meta(),kind:'time',description:'Edit',minutes:10,variantOwner:{groupId:group.id,optionId:option.id},manuallyModified:true}]};expect(changeVariant(item,group.id,option.id,false,{materializeTravel:()=>{throw new Error('unused')}}).ok).toBe(false);});
  it('richiede una scelta esplicita quando il gruppo non ha default',()=>{const option={...meta(),name:'Manuale',subItems:[]};const group={...meta(),name:'Senza default',options:[option]};const item:QuoteItem={...meta(),name:'X',variantGroups:[group],variantSelections:[],subItems:[]};expect(applyVariantSelections(item,{}, {materializeTravel:()=>{throw new Error('unused')}}).ok).toBe(false);expect(applyVariantSelections(item,{[group.id]:option.id},{materializeTravel:()=>{throw new Error('unused')}}).ok).toBe(true);});
  it('rappresenta Nessuna con zero sottovoci e lascia la voce non calcolabile',()=>{const none={...meta(),name:'Nessuna',subItems:[]};const group={...meta(),name:'Gestione cliente',options:[none],defaultOptionId:none.id};const item:QuoteItem={...meta(),name:'Solo variante',variantGroups:[group],variantSelections:[],subItems:[]};const applied=applyVariantSelections(item,{}, {materializeTravel:()=>{throw new Error('unused')}});expect(applied.ok).toBe(true);if(!applied.ok)return;expect(applied.value.subItems).toEqual([]);expect(calculateItem(applied.value,'100').blockers.join(' ')).toContain('tempo');});
});
