import { calculateItem, calculateProfile, calculateQuote, calculateTravel, calculateVehicleCost, previewProfile } from '../domain/calculations';
import { createLocalClient, deleteLocalClient, searchLocalClients, snapshotLocalClient, updateLocalClient } from '../domain/clients';
import { confirmProfile, copyProfileToYear, saveProfileRevision } from '../domain/profiles';
import { buildExportLines, createPendingAttempt, needsRepeatWarning } from '../domain/export';
import { cloneTemplate, previewTemplate, reusableFromQuoteSubItem, templateFromQuote } from '../domain/catalog';
import { applyVariantSelections, changeVariant, validateVariantGroups } from '../domain/variants';
import { refreshQuote, snapshotProfile } from '../domain/refresh';
import { createBlankProfile, createFiscalPreset2026, meta, type CashDocument, type EconomicProfile,
  type Quote, type QuoteItem, type QuoteSubItem, type SiteSnapshot, type SubItemDefinition, type Vehicle } from '../domain/model';
import { state } from './state';

type View = 'dashboard' | 'quotes' | 'clients' | 'resources' | 'catalog' | 'settings';
let view: View = 'dashboard';
let activeQuoteId: string | undefined;
let activeProfileId: string | undefined;
let hasFicToken = false;
let ficConnectionError = false;
let ficSetupInfo:{clientId:string;requiredScopes:string[]}={clientId:'',requiredScopes:[]};
const vehicleCostPreviews = new Map<string,{ costPerKm:string; referenceDate:string }>();
const root = document.querySelector<HTMLDivElement>('#app')!;

const esc = (value: unknown): string => String(value ?? '').replace(/[&<>"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[char]!);
const eur = (value?: string): string => value === undefined ? '—' : new Intl.NumberFormat('it-IT', { style: 'currency', currency: 'EUR' }).format(Number(value));
const hours = (minutes?: number): string => minutes === undefined ? '—' : `${Math.floor(minutes / 60)}h ${minutes % 60}m`;
const field = (label: string, name: string, value: unknown, type = 'text', extra = '') => `<label>${esc(label)}<input name="${name}" value="${esc(value)}" type="${type}" ${extra}></label>`;
const statusClass = (): string => state.status === 'Salvato' ? '' : state.status.includes('Errore') || state.status.includes('Conflitto') ? 'bad' : 'warn';
const documentNow = (): CashDocument | undefined => state.document;
const selectedQuote = (): Quote | undefined => documentNow()?.quotes.find(quote => quote.id === activeQuoteId);
const profileFor = (quote?: Quote): EconomicProfile | undefined => documentNow()?.profiles.find(profile => profile.id === quote?.profileId);
const siteSnapshot = (id: string): SiteSnapshot | undefined => { const site = documentNow()?.sites.find(value => value.id === id); return site ? { sourceId: site.id, name: site.name, address: site.address, ...(site.oneWayKm !== undefined ? { oneWayKm: site.oneWayKm } : {}) } : undefined; };

function nav(): string {
  const entries: Array<[View, string]> = [['dashboard', 'Panoramica'], ['quotes', 'Preventivi'], ['clients', 'Clienti'], ['resources', 'Risorse'], ['catalog', 'Catalogo'], ['settings', 'Impostazioni']];
  return `<aside class="sidebar"><div class="brand">Cash<small>preventivi verificabili</small></div><nav class="nav">${entries.map(([key, label]) => `<button data-view="${key}" class="${view === key ? 'active' : ''}">${label}</button>`).join('')}</nav><p class="hint">Un solo file JSON è la fonte canonica. Prima di cambiare postazione attendi sempre “Salvato” e la sincronizzazione di Google Drive.</p></aside>`;
}

function errorBox(): string {
  return state.error ? `<div class="notice error"><strong>${esc(state.error.message)}</strong>${state.error.action ? `<div>${esc(state.error.action)}</div>` : ''}${state.error.details?.length ? `<div class="small">${state.error.details.map(esc).join('<br>')}</div>` : ''}<button class="ghost" data-action="dismiss-error">Chiudi</button></div>` : '';
}

function topbar(): string {
  return `<header class="topbar"><div><h1>${({ dashboard: 'Panoramica', quotes: 'Preventivi', clients: 'Clienti', resources: 'Risorse', catalog: 'Catalogo', settings: 'Impostazioni' })[view]}</h1><div class="small muted">${esc(state.session?.path ?? '')}</div></div><div class="actions"><span class="status ${statusClass()}">${esc(state.status)}</span><button class="secondary" data-action="open">Apri</button><button class="ghost" data-action="recovery">Copia di recupero</button><button class="ghost" data-action="restore-backup">Ripristina backup</button><button data-action="save" ${state.status === 'Salvato' ? 'disabled' : ''}>Salva ora</button></div></header>`;
}

function dashboard(doc: CashDocument): string {
  const profile = doc.profiles.find(candidate=>candidate.id===activeProfileId) ?? doc.profiles[0];
  const analysis = profile?.confirmed ? calculateProfile(profile, doc.businessCosts) : undefined;
  const preview = profile ? previewProfile(profile, doc.businessCosts) : undefined;
  const values = analysis?.ok ? analysis.value : undefined;
  const previewValues = preview?.ok ? preview.value : undefined;
  return `<div class="grid">
    <section class="card"><div class="muted small">Valore medio da generare</div><div class="metric">${values ? `${eur(values.hourlyTarget)}/h` : '—'}</div><div class="small muted">Non è una tariffa obbligatoria.</div></section>
    <section class="card"><div class="muted small">Netto fiscale stimato</div><div class="metric">${eur(values?.fiscalNet)}</div><div class="small muted">Stima interna, non fiscale/contabile.</div></section>
    <section class="card"><div class="muted small">Disponibile stimato</div><div class="metric">${eur(values?.availableIncome)}</div><div class="small muted">Dopo costi aziendali e spese specifiche.</div></section>
    ${!profile ? `<section class="card full empty"><h2>Configura il profilo 2026</h2><p>Parti dal preset previsto dalla specifica e conferma i parametri.</p><button data-action="add-preset">Crea preset 2026</button></section>` : `
    <section class="card wide"><h2>Profilo economico ${profile.year}</h2>${!profile.confirmed ? '<div class="notice">Il profilo fiscale deve essere confermato prima della proiezione.</div>' : ''}
      <form data-form="profile" class="form-grid">
        ${field('Anno fiscale', 'year', profile.year, 'number', 'min="2000" max="2200" step="1" required')}
        ${field('Fatturato obiettivo', 'revenueTarget', profile.revenueTarget, 'number', 'min="0" step="0.01" required')}
        ${field('Spese specifiche annue', 'specificAnnualExpenses', profile.specificAnnualExpenses, 'number', 'min="0" step="0.01" required')}
        ${field('Ore lavorative/giorno', 'hoursPerDay', profile.capacity.hoursPerDay, 'number', 'min="0.01" max="24" step="0.01" required')}
        ${field('Tempo dedicabile (%)', 'clientTimePercentage', profile.capacity.clientTimePercentage, 'number', 'min="0.0001" max="100" step="0.0001" required')}
        ${field('Ferie (giorni)', 'vacationDays', profile.capacity.vacationDays, 'number', 'min="0" step="1" required')}
        ${field('Malattia / imprevisti', 'unplannedDays', profile.capacity.unplannedDays, 'number', 'min="0" step="1" required')}
        ${field('Velocità media trasferta (km/h)', 'travelSpeedKmh', profile.capacity.travelSpeedKmh ?? '', 'number', 'min="0.1" step="0.1"')}
        ${field('Festività locali (MM-GG o AAAA-MM-GG, separate da virgola)', 'localHolidays', profile.capacity.localHolidays.map(holiday=>holiday.kind==='recurring'?`${String(holiday.month).padStart(2,'0')}-${String(holiday.day).padStart(2,'0')}`:holiday.date).join(', '))}
        ${field('ATECO 2025', 'atecoCode', profile.fiscal.atecoCode, 'text', 'required')}
        ${field('Coefficiente redditività (%)', 'profitabilityCoefficient', profile.fiscal.profitabilityCoefficient, 'number', 'min="0.0001" max="100" step="0.0001" required')}
        ${field('Aliquota Gestione Separata (%)', 'contributionRate', profile.fiscal.contributionRate, 'number', 'min="0" max="100" step="0.0001" required')}
        ${field('Massimale contributivo', 'contributionCeiling', profile.fiscal.contributionCeiling, 'number', 'min="0" step="0.01" required')}
        <label>Fase attività<select name="activityPhase"><option value="ordinary" ${profile.fiscal.activityPhase==='ordinary'?'selected':''}>Oltre 5 periodi / non spettante</option><option value="reduced_eligible" ${profile.fiscal.activityPhase==='reduced_eligible'?'selected':''}>Primi 5 periodi, agevolazione spettante</option></select></label>
        ${field('Aliquota agevolata (%)', 'reducedSubstituteTaxRate', profile.fiscal.reducedSubstituteTaxRate, 'number', 'min="0" max="100" step="0.0001" required')}
        ${field('Aliquota ordinaria (%)', 'ordinarySubstituteTaxRate', profile.fiscal.ordinarySubstituteTaxRate, 'number', 'min="0" max="100" step="0.0001" required')}
        ${field('Soglia ordinaria', 'ordinaryThreshold', profile.fiscal.ordinaryThreshold, 'number', 'min="0" step="0.01" required')}
        ${field('Soglia cessazione', 'cessationThreshold', profile.fiscal.cessationThreshold, 'number', 'min="0" step="0.01" required')}
        <label class="full"><span><input name="reducedEligibilityConfirmed" type="checkbox" ${profile.fiscal.reducedEligibilityConfirmed ? 'checked' : ''}> Confermo i requisiti per l’aliquota agevolata</span></label>
        <label class="full"><span><input name="ordinaryApplicabilityConfirmed" type="checkbox" ${profile.fiscal.ordinaryApplicabilityConfirmed ? 'checked' : ''}> Confermo l’applicabilità oltre la soglia ordinaria</span></label>
        <div id="profile-preview" class="full notice">Anteprima: aliquota effettiva <strong>${previewValues?.effectiveTaxRate ?? '—'}%</strong> · reddito forfettario ${eur(previewValues?.forfaitIncome)} · base contributiva ${eur(previewValues?.contributionBase)} · contributi ${eur(previewValues?.contributions)} · base imposta ${eur(previewValues?.taxBase)} · imposta ${eur(previewValues?.substituteTax)}</div>
        <div class="full actions"><button name="profileAction" value="save">Salva come Da verificare</button><button name="profileAction" value="confirm">Conferma profilo</button><button type="button" class="secondary" data-action="copy-profile" data-id="${profile.id}">Copia per nuovo anno</button></div>
      </form></section>
    <section class="card"><h2>Capacità</h2><div class="list"><div class="row"><span>Giorni teorici</span><strong>${values?.theoreticalWorkdays ?? '—'}</strong></div><div class="row"><span>Giorni disponibili</span><strong>${values?.availableDays ?? '—'}</strong></div><div class="row"><span>Ore clienti</span><strong>${values ? (values.availableClientMinutes / 60).toFixed(1) : '—'}</strong></div><div class="row"><span>Costi annui</span><strong>${eur(values?.annualBusinessCosts)}</strong></div></div>${analysis && !analysis.ok ? `<div class="notice error">${esc(analysis.error.message)}</div>` : ''}</section>`}
    <section class="card full"><h2>Preventivi recenti</h2>${doc.quotes.length ? `<div class="list">${doc.quotes.slice(-5).reverse().map(q => `<div class="row"><div><div class="row-title">${esc(q.items.map(i => i.name).join(', ') || 'Preventivo incompleto')}</div><div class="row-detail">${esc(q.date)} · ${q.items.length} voci</div></div><button data-open-quote="${q.id}">Apri</button></div>`).join('')}</div>` : '<div class="empty">Nessun preventivo. Creane uno dalla sezione Preventivi.</div>'}</section>
  </div>`;
}

function clients(doc: CashDocument): string {
  return `<div class="grid"><section class="card"><h2>Nuovo Cliente locale</h2><form data-form="local-client" class="form-grid">
    ${field('Denominazione', 'displayName', '', 'text', 'required')}${field('Partita IVA (facoltativa)', 'vatNumber', '')}<button class="full">Crea cliente</button></form></section>
    <section class="card wide"><h2>Anagrafica locale</h2><form data-form="client-filter" class="actions">${field('Cerca per nome o P.IVA', 'query', '')}<button>Cerca</button></form><div id="local-client-list" class="list" style="margin-top:.8rem">
    ${doc.localClients.length ? doc.localClients.map(client => `<div class="row"><div><div class="row-title">${esc(client.displayName)}</div><div class="row-detail">${esc(client.vatNumber ?? 'P.IVA non indicata')}</div></div><div class="row-actions"><button class="secondary" data-action="edit-local-client" data-id="${client.id}">Modifica</button><button class="danger" data-delete="local-client:${client.id}">Elimina</button></div></div>`).join('') : '<div class="empty">Nessun Cliente locale.</div>'}</div></section></div>`;
}

function resources(doc: CashDocument): string {
  return `<div class="grid"><section class="card"><h2>Costi aziendali</h2><form data-form="cost" class="form-grid">${field('Categoria','category','')}${field('Descrizione','description','')}${field('Importo mensile','monthlyAmount','0.00','number','min="0" step="0.01"')}<button class="full">Aggiungi</button></form></section>
  <section class="card"><h2>Veicoli</h2><form data-form="vehicle" class="form-grid">${field('Nome','name','')}${`<label>Carburante<select name="fuel"><option>Benzina</option><option>Gasolio</option><option>GPL</option><option>Metano</option></select></label>`}${field('Consumo /100 km','consumption','6.00','number','min="0.01" step="0.01"')}${field('Km annui','annualKm','10000','number','min="1" step="0.1"')}${field('Assicurazione annua','annualInsurance','0.00','number','min="0" step="0.01"')}${field('Bollo annuo','annualTax','0.00','number','min="0" step="0.01"')}${field('Manutenzione annua','annualMaintenance','0.00','number','min="0" step="0.01"')}<button class="full">Aggiungi</button></form></section>
  <section class="card"><h2>Sedi</h2><form data-form="site" class="form-grid">${field('Nome','name','')}${field('Indirizzo','address','')}<label>Cliente locale associato<select name="localClientId"><option value="">Nessuno</option>${doc.localClients.map(client=>`<option value="${client.id}">${esc(client.displayName)}</option>`).join('')}</select></label>${field('Km sola andata','oneWayKm','','number','min="0" step="0.1"')}<button class="full">Aggiungi</button></form></section>
  <section class="card full"><div class="split"><div><h2>Costi</h2>${listRows(doc.businessCosts.map(x => ({ id:x.id,title:`${x.category} · ${x.description}`,detail:`${eur(x.monthlyAmount)}/mese`,kind:'cost' })) )}</div><div><h2>Veicoli</h2>${listRows(doc.vehicles.map(x => ({id:x.id,title:x.name,detail:`${x.fuel} · ${x.consumption} ${x.consumptionUnit}${vehicleCostPreviews.has(x.id)?` · ${eur(vehicleCostPreviews.get(x.id)!.costPerKm)}/km · dato ${vehicleCostPreviews.get(x.id)!.referenceDate}`:''}`,kind:'vehicle'})))}</div><div><h2>Sedi</h2>${doc.sites.length?`<div class="list">${doc.sites.map(site=>`<div class="row"><div><strong>${esc(site.name)}</strong><div class="row-detail">${esc(site.address)}${site.oneWayKm!==undefined?` · ${site.oneWayKm} km`:''} · ${esc(site.client?.displayName??'nessun cliente')}</div></div><div class="row-actions"><button class="secondary" data-action="edit-site" data-id="${site.id}">Modifica</button>${doc.settings.fic.enabled?`<button class="secondary" data-action="associate-remote-site" data-id="${site.id}">Cliente FIC</button>`:''}<button class="danger" data-delete="site:${site.id}">Elimina</button></div></div>`).join('')}</div>`:'<div class="empty">Nessuna Sede</div>'}</div></div></section></div>`;
}

function listRows(rows: Array<{id:string;title:string;detail:string;kind:string}>): string {
  return rows.length ? `<div class="list">${rows.map(row => `<div class="row"><div class="row-main"><div class="row-title">${esc(row.title)}</div><div class="row-detail">${esc(row.detail)}</div></div><div class="row-actions"><button class="secondary" data-action="edit-${row.kind}" data-id="${row.id}">Modifica</button>${row.kind==='vehicle'?`<button class="secondary" data-action="check-vehicle-cost" data-id="${row.id}">Calcola costo/km</button>`:''}<button class="danger" data-delete="${row.kind}:${row.id}">Elimina</button></div></div>`).join('')}</div>` : '<div class="empty">Nessun elemento</div>';
}

function catalog(doc: CashDocument): string {
  return `<div class="grid"><section class="card"><h2>Nuova sottovoce</h2><form data-form="catalog" class="form-grid"><label>Tipo<select name="kind"><option value="time">Tempo</option><option value="expense">Spesa</option><option value="travel">Trasferta</option></select></label>${field('Descrizione','description','')}${field('Minuti / importo','value','30','number','min="0" step="0.01"')}${field('Occorrenze Trasferta','occurrences','1','number','min="1" step="1"')}<label>Modalità tempo Trasferta<select name="timeMode"><option value="automatic">Automatica</option><option value="manual">Manuale (usa Minuti)</option></select></label><label><span><input type="checkbox" name="roundTrip" checked> Andata e ritorno</span></label><button class="full">Aggiungi</button></form></section><section class="card wide"><h2>Sottovoci riutilizzabili</h2>${listRows(doc.catalog.subItems.map(x => ({id:x.id,title:x.description,detail:x.kind === 'time' ? `${x.minutes} min` : x.kind === 'expense' ? eur(x.amount) : `Trasferta ${x.roundTrip?'A/R':'solo andata'} · ${x.occurrences} occorrenze · ${x.timeMode}`,kind:'catalog'})))}</section><section class="card full"><h2>Template</h2>${doc.catalog.templates.length ? `<div class="list">${doc.catalog.templates.map(t => `<div class="row"><div><div class="row-title">${esc(t.name)}</div><div class="row-detail">${t.items.length} voci · copia indipendente</div></div><div class="row-actions"><button class="secondary" data-action="edit-template" data-id="${t.id}">Apri e modifica</button><button class="danger" data-delete="template:${t.id}">Elimina</button></div></div>`).join('')}</div>` : '<div class="empty">Salva una o più voci da un preventivo per creare un nuovo template.</div>'}</section></div>`;
}

function quoteList(doc: CashDocument): string {
  return `<div class="grid"><section class="card full"><div class="actions"><button data-action="new-quote">Nuovo preventivo</button></div><div class="list" style="margin-top:1rem">${doc.quotes.length ? doc.quotes.map(q => `<div class="row"><div><div class="row-title">${esc(q.items.map(i => i.name).join(', ') || 'Preventivo incompleto')}</div><div class="row-detail">${q.date} · ${q.client?.displayName ?? 'Nessun cliente'} · ${q.items.length} voci</div></div><div class="row-actions"><button data-open-quote="${q.id}">Apri</button><button class="danger" data-delete="quote:${q.id}">Elimina</button></div></div>`).join('') : '<div class="empty">Nessun preventivo</div>'}</div></section></div>`;
}

function quotes(doc: CashDocument): string {
  const quote = selectedQuote();
  if (!quote) return quoteList(doc);
  const hourly = quote.profileSnapshot?.hourlyTarget;
  const total = hourly ? calculateQuote(quote.items, hourly) : undefined;
  return `<div class="actions" style="margin-bottom:1rem"><button class="secondary" data-action="back-quotes">← Elenco</button><button data-action="add-item">Aggiungi voce</button><button class="secondary" data-action="insert-template" ${doc.catalog.templates.length?'':'disabled'}>Inserisci template</button><button class="ghost" data-action="save-template" ${quote.items.length ? '' : 'disabled'}>Salva come template</button><button class="ghost" data-action="refresh-quote">Aggiorna valori correnti</button><button data-action="export-quote" ${doc.settings.fic.enabled ? '' : 'disabled'}>Anteprima ed esporta</button></div>
  <div class="split"><div class="stack"><section class="card full"><h2>Dati preventivo</h2><form data-form="quote" class="form-grid">${field('Data','date',quote.date,'date')}
    <label>Profilo<select name="profileId"><option value="">Incompleto</option>${doc.profiles.map(p => `<option value="${p.id}" ${quote.profileId===p.id?'selected':''}>${p.year}${p.confirmed?'':' · da confermare'}</option>`).join('')}</select></label>
    <label>Sede principale<select name="mainSiteId"><option value="">Nessuna</option>${doc.sites.map(s=>`<option value="${s.id}" ${quote.mainSite?.sourceId===s.id?'selected':''}>${esc(s.name)}</option>`).join('')}</select></label>
    ${field('Provvigione esterna','commission',quote.commission??'','number','min="0" step="0.01"')}<button class="full">Aggiorna dati</button></form>
    ${quote.client ? `<div class="notice">Cliente: <strong>${esc(quote.client.displayName)}</strong> · ${quote.client.source === 'local' ? 'locale' : 'Fatture in Cloud'} · P.IVA ${esc(quote.client.vatNumber ?? '—')} <button class="ghost" data-action="clear-quote-client">Rimuovi</button>${quote.client.source === 'fatture_in_cloud' ? '<button class="secondary" data-action="copy-remote-client">Copia come Cliente locale</button>' : ''}</div>` : `<form data-form="quote-local-client" class="actions"><label>Cliente locale<select name="localClientId"><option value="">Nessun cliente</option>${doc.localClients.map(client=>`<option value="${client.id}">${esc(client.displayName)}</option>`).join('')}</select></label><button>Seleziona</button></form>${doc.settings.fic.enabled ? `<form data-form="client-search" class="actions">${field('Cerca cliente Fatture in Cloud','query','')}<button>Cerca live</button></form><div id="client-results"></div>` : '<div class="notice">Fatture in Cloud è disattivato. Il ciclo locale resta disponibile.</div>'}`}</section>
    ${quote.items.map(item => quoteItemCard(item, hourly, doc)).join('') || '<div class="empty">Aggiungi almeno una voce commerciale.</div>'}</div>
    <aside class="stack"><section class="card full"><h2>Analisi complessiva</h2>${total ? analysisHtml(total) : '<div class="notice">Associa un profilo calcolabile.</div>'}</section><section class="card full"><h3>Snapshot</h3><div class="small muted">Profilo ${quote.profileSnapshot ? `${quote.profileSnapshot.year} rev. ${quote.profileSnapshot.revision}` : 'non associato'}<br>Revisione snapshot ${quote.snapshotRevision}<br>${quote.snapshotUpdatedAt ? `Aggiornato ${esc(quote.snapshotUpdatedAt)}` : 'Mai aggiornato'}</div></section></aside></div>`;
}

function analysisHtml(a: ReturnType<typeof calculateItem> | ReturnType<typeof calculateQuote>): string {
  return `<div class="analysis"><div><span class="small muted">Tempo</span><strong>${hours(a.minutes)}</strong></div><div><span class="small muted">Spese</span><strong>${eur(a.expenses)}</strong></div><div><span class="small muted">Teorico</span><strong>${eur(a.theoreticalValue)}</strong></div><div><span class="small muted">Resa</span><strong>${a.yieldPerHour ? `${eur(a.yieldPerHour)}/h` : '—'}</strong></div><div><span class="small muted">Scostamento</span><strong>${a.deviationPercent ? `${a.deviationPercent}%` : '—'}</strong></div><div><span class="small muted">Tempo coerente</span><strong>${hours(a.coherentMinutes)}</strong></div></div>${a.deficit ? `<div class="notice error">Disavanzo: ${eur(a.deficit)}</div>` : ''}${a.blockers.length ? `<div class="notice">${a.blockers.map(esc).join('<br>')}</div>` : ''}`;
}

function quoteItemCard(item: QuoteItem, hourly: string | undefined, doc: CashDocument): string {
  const analysis = hourly ? calculateItem(item, hourly) : undefined;
  return `<section class="card full item"><div class="row"><div><h2>${esc(item.name)}</h2><span class="pill">${item.subItems.length} sottovoci</span></div><div class="row-actions"><button class="secondary" data-action="rename-item" data-id="${item.id}">Rinomina</button><button class="danger" data-delete="item:${item.id}">Elimina</button></div></div>
    <form data-form="item-price" data-id="${item.id}" class="form-grid" style="margin-top:.8rem">${field('Prezzo scelto','chosenPrice',item.chosenPrice??'','number','min="0" step="0.01"')}${field('Prezzo di riferimento','referenceAmount',item.referencePrice?.amount??'','number','min="0" step="0.01"')}${field('Mese riferimento','referencePeriod',item.referencePrice?.period??'','month')}<button>Aggiorna prezzi</button></form>${item.referencePrice?.foiEvidence?`<div class="notice">Rivalutato: <strong>${eur(item.referencePrice.foiEvidence.revaluedAmount)}</strong> · ${item.referencePrice.foiEvidence.fromPeriod} → ${item.referencePrice.foiEvidence.toPeriod} · basi ${esc(item.referencePrice.foiEvidence.fromBase)} / ${esc(item.referencePrice.foiEvidence.toBase)} · acquisito ${esc(item.referencePrice.foiEvidence.acquiredAt)}</div>`:''}
    <div class="list" style="margin-top:.8rem">${item.subItems.map(sub => `<div class="row"><div><div class="row-title">${esc(sub.description)}</div><div class="row-detail">${sub.kind==='time'?`${sub.minutes} min`:sub.kind==='expense'?eur(sub.amount):`${sub.totalDistanceKm} km · ${hours(sub.totalMinutes)} · ${eur(sub.totalCost)}`}${sub.variantOwner?' · variante':''}</div></div><div class="row-actions"><button class="secondary" data-action="edit-sub" data-id="${item.id}:${sub.id}">Modifica</button><button class="secondary" data-action="save-sub" data-id="${item.id}:${sub.id}">Salva nel catalogo</button><button class="danger" data-delete="sub:${item.id}:${sub.id}">×</button></div></div>`).join('') || '<div class="empty">La voce richiede tempo positivo per essere calcolabile.</div>'}</div>
    ${item.variantGroups.map(group => `<label style="margin-top:.8rem">${esc(group.name)}<select data-variant="${item.id}:${group.id}">${group.options.map(option => `<option value="${option.id}" ${item.variantSelections.some(s=>s.groupId===group.id&&s.optionId===option.id)?'selected':''}>${esc(option.name)}</option>`).join('')}</select></label>`).join('')}
    <div class="tabs" style="margin-top:.8rem"><button class="secondary" data-action="add-time" data-id="${item.id}">+ Tempo</button><button class="secondary" data-action="add-expense" data-id="${item.id}">+ Spesa</button><button class="secondary" data-action="add-travel" data-id="${item.id}">+ Trasferta</button><button class="secondary" data-action="add-catalog" data-id="${item.id}" ${doc.catalog.subItems.length?'':'disabled'}>+ Dal catalogo</button><button class="secondary" data-action="add-variant" data-id="${item.id}">+ Variante</button></div>${analysis ? analysisHtml(analysis) : ''}</section>`;
}

function settings(doc: CashDocument): string {
  const fic = doc.settings.fic;
  const deviceState = !fic.enabled ? 'Disattivata' : ficConnectionError || fic.lastVerification?.result === 'error' ? 'Errore collegamento' : !hasFicToken ? 'Richiede configurazione locale' : 'Attiva';
  return `<div class="grid"><section class="card"><h2>Pianificazione</h2><form data-form="settings" class="form-grid">${field('Regione / provincia MIMIT','fuelTerritory',doc.settings.fuelTerritory??'')}<button class="full">Salva</button></form></section>
  <section class="card wide"><h2>Fatture in Cloud</h2><div class="notice"><strong>${deviceState}</strong><br>${fic.enabled ? `${esc(fic.company?.name ?? 'Azienda non configurata')} · ${esc(fic.product?.name ?? 'Prodotto non configurato')} · ultima verifica ${esc(fic.lastVerification?.at ?? '—')}` : 'Nessuna chiamata al servizio. Tutte le funzioni locali restano disponibili.'}</div>
  <p class="small muted">Client ID app privata: <strong>${esc(ficSetupInfo.clientId||'non configurato nella build')}</strong><br>Permessi: ${esc(ficSetupInfo.requiredScopes.join(', '))}. Il token resta nel Gestore credenziali di Windows.</p><div class="actions">
  ${fic.enabled ? '<button data-action="disable-fic" class="secondary">Disattiva</button>' : '<button data-action="activate-fic">Usa Fatture in Cloud</button>'}
  <button data-action="activate-fic" class="ghost">${fic.enabled ? 'Riconfigura postazione' : 'Avvia configurazione guidata'}</button>
  <button data-action="remove-fic" class="danger">Rimuovi collegamento</button></div></section>
  <section class="card full"><div class="actions"><h2>Profili annuali</h2><button data-action="add-blank-profile">Nuovo vuoto</button></div><div class="list">${doc.profiles.map(profile=>`<div class="row"><div><strong>${profile.year}</strong><div class="row-detail">rev. ${profile.revision} · ${profile.confirmed?'Confermato':'Da verificare'}</div></div><div class="row-actions"><button data-action="edit-profile" data-id="${profile.id}">Modifica</button><button class="secondary" data-action="copy-profile" data-id="${profile.id}">Copia per nuovo anno</button><button class="danger" data-delete="profile:${profile.id}">Elimina</button></div></div>`).join('') || '<div class="empty">Nessun profilo.</div>'}</div></section>
  <section class="card full notice"><strong>Uso su più postazioni</strong><br>Chiudi Cash solo quando compare “Salvato”, attendi la sincronizzazione Drive sulla prima postazione e poi sulla seconda. L’uso simultaneo non è supportato.</section></div>`;
}

function render(): void {
  const doc = documentNow();
  if (!doc) { root.innerHTML = `<main class="onboarding"><section class="welcome"><span class="pill">Client desktop locale</span><h1>Preventivi con una base verificabile.</h1><p>Cash mette insieme obiettivo economico, tempo, trasferte e spese. Il prezzo finale resta sempre una tua decisione.</p>${errorBox()}<div class="actions"><button data-action="create">Crea archivio</button><button class="secondary" data-action="open">Apri archivio</button></div><p class="small">Per l’uso con Google Drive scegli una cartella “Il mio Drive” in modalità Duplica file.</p></section></main>`; return; }
  const body = view === 'dashboard' ? dashboard(doc) : view === 'quotes' ? quotes(doc) : view === 'clients' ? clients(doc) : view === 'resources' ? resources(doc) : view === 'catalog' ? catalog(doc) : settings(doc);
  root.innerHTML = `<div class="shell">${nav()}<main class="main">${topbar()}${errorBox()}${body}</main></div>`;
}

function mutateEntityList(kind: string, id: string): void {
  if (kind === 'local-client') {
    const doc = documentNow(); if (!doc) return;
    const result = deleteLocalClient(doc, id);
    if (!result.ok) { state.error = result.error; render(); return; }
    state.mutate(target => { target.localClients = result.value.localClients; });
    return;
  }
  if (kind === 'profile') {
    const references=documentNow()?.quotes.filter(quote=>quote.profileId===id).map(quote=>`${quote.date} · ${quote.items.map(item=>item.name).join(', ')||'preventivo incompleto'}`)??[];
    if(references.length){state.error={code:'CONFLICT',field:'profile',message:'Il profilo è ancora il riferimento corrente di uno o più preventivi.',details:references};render();return;}
  }
  state.mutate(doc => {
    if (kind === 'cost') doc.businessCosts = doc.businessCosts.filter(x=>x.id!==id);
    else if (kind === 'vehicle') doc.vehicles = doc.vehicles.filter(x=>x.id!==id);
    else if (kind === 'site') doc.sites = doc.sites.filter(x=>x.id!==id);
    else if (kind === 'catalog') doc.catalog.subItems = doc.catalog.subItems.filter(x=>x.id!==id);
    else if (kind === 'template') doc.catalog.templates = doc.catalog.templates.filter(x=>x.id!==id);
    else if (kind === 'profile') { doc.profiles = doc.profiles.filter(x=>x.id!==id); if(activeProfileId===id)activeProfileId=undefined; }
    else if (kind === 'quote') { doc.quotes = doc.quotes.filter(x=>x.id!==id); if(activeQuoteId===id)activeQuoteId=undefined; }
    else if (kind === 'item') { const q=selectedQuote(); if(q){ const target=doc.quotes.find(x=>x.id===q.id)!; target.items=target.items.filter(x=>x.id!==id); } }
    else if (kind === 'sub') { const [itemId,subId]=id.split(':'); const q=selectedQuote(); if(q){const item=doc.quotes.find(candidate=>candidate.id===q.id)?.items.find(candidate=>candidate.id===itemId);if(item)item.subItems=item.subItems.filter(sub=>sub.id!==subId);} }
  });
}

const promptRequired = (message: string, initial = ''): string | undefined => { const value = window.prompt(message, initial)?.trim(); return value || undefined; };
const parseLocalHolidays = (value:string):EconomicProfile['capacity']['localHolidays'] => value.split(',').map(item=>item.trim()).filter(Boolean).map((item,index)=>{
  if(/^\d{4}-\d{2}-\d{2}$/.test(item))return{kind:'specific' as const,name:`Festività locale ${index+1}`,date:item};
  const match=/^(\d{2})-(\d{2})$/.exec(item);return{kind:'recurring' as const,name:`Festività locale ${index+1}`,month:Number(match?.[1]??0),day:Number(match?.[2]??0)};
});

async function action(name: string, id?: string): Promise<void> {
  const doc = documentNow();
  if (name==='create') return state.create(); if(name==='open') return state.open(); if(name==='save') return state.save(); if(name==='recovery'){await state.recovery();return;} if(name==='restore-backup')return state.restoreBackup();
  if(name==='dismiss-error') return state.clearError();
  if(!doc) return;
  if(name==='check-vehicle-cost'&&id){const vehicle=doc.vehicles.find(candidate=>candidate.id===id);if(!vehicle||!doc.settings.fuelTerritory){window.alert('Configurare veicolo e territorio MIMIT.');return;}const fuel=await window.cash.mimit.latestFuelPrice({territory:doc.settings.fuelTerritory,fuel:vehicle.fuel});if(!fuel.ok){state.error=fuel.error;render();return;}const calculated=calculateVehicleCost(vehicle,fuel.value);if(!calculated.ok){state.error=calculated.error;render();return;}vehicleCostPreviews.set(vehicle.id,{costPerKm:calculated.value.costPerKm,referenceDate:fuel.value.referenceDate});render();}
  else if(name==='edit-cost'&&id){const cost=doc.businessCosts.find(candidate=>candidate.id===id);if(!cost)return;const category=promptRequired('Categoria',cost.category);const description=promptRequired('Descrizione',cost.description);const amount=promptRequired('Importo mensile',cost.monthlyAmount);if(!category||!description||amount===undefined||Number(amount)<0)return;state.mutate(d=>{const target=d.businessCosts.find(candidate=>candidate.id===id)!;Object.assign(target,{category,description,monthlyAmount:Number(amount).toFixed(2),updatedAt:new Date().toISOString()});});}
  else if(name==='edit-vehicle'&&id){const vehicle=doc.vehicles.find(candidate=>candidate.id===id);if(!vehicle)return;const value={name:promptRequired('Nome veicolo',vehicle.name),fuel:promptRequired('Carburante: Benzina, Gasolio, GPL o Metano',vehicle.fuel) as Vehicle['fuel']|undefined,consumption:promptRequired('Consumo per 100 km',vehicle.consumption),annualKm:promptRequired('Km annui',vehicle.annualKm),annualInsurance:promptRequired('Assicurazione annua',vehicle.annualInsurance),annualTax:promptRequired('Bollo annuo',vehicle.annualTax),annualMaintenance:promptRequired('Manutenzione annua',vehicle.annualMaintenance)};if(Object.values(value).some(item=>item===undefined)||!['Benzina','Gasolio','GPL','Metano'].includes(value.fuel!))return;state.mutate(d=>{const target=d.vehicles.find(candidate=>candidate.id===id)!;Object.assign(target,{...value,consumptionUnit:value.fuel==='Metano'?'kg/100km':'l/100km',annualInsurance:Number(value.annualInsurance).toFixed(2),annualTax:Number(value.annualTax).toFixed(2),annualMaintenance:Number(value.annualMaintenance).toFixed(2),updatedAt:new Date().toISOString()});});vehicleCostPreviews.delete(id);}
  else if(name==='edit-site'&&id){const site=doc.sites.find(candidate=>candidate.id===id);if(!site)return;const siteName=promptRequired('Nome Sede',site.name);const address=promptRequired('Indirizzo',site.address);const km=window.prompt('Km sola andata (vuoto = non configurati)',site.oneWayKm??'');const clientChoice=window.prompt(`Cliente: P conserva, 0 nessuno, oppure numero Cliente locale\n${doc.localClients.map((client,index)=>`${index+1}. ${client.displayName}`).join('\n')}`,'P');if(!siteName||!address||km===null||clientChoice===null)return;const selected=doc.localClients[Number(clientChoice)-1];state.mutate(d=>{const target=d.sites.find(candidate=>candidate.id===id)!;target.name=siteName;target.address=address;target.oneWayKm=km.trim()?Number(km).toFixed(1):undefined;if(clientChoice.toLocaleUpperCase('it')==='P'){/* conserva */}else if(clientChoice==='0')target.client=undefined;else if(selected)target.client={source:'local',localClientId:selected.id,displayName:selected.displayName};target.updatedAt=new Date().toISOString();});}
  else if(name==='edit-catalog'&&id){const reusable=doc.catalog.subItems.find(candidate=>candidate.id===id);if(!reusable)return;const description=promptRequired('Descrizione',reusable.description);if(!description)return;if(reusable.kind==='time'){const minutes=promptRequired('Minuti interi positivi',String(reusable.minutes));if(!minutes)return;state.mutate(d=>Object.assign(d.catalog.subItems.find(candidate=>candidate.id===id)!,{description,minutes:Number(minutes),updatedAt:new Date().toISOString()}));}else if(reusable.kind==='expense'){const amount=promptRequired('Importo',reusable.amount);if(!amount)return;state.mutate(d=>Object.assign(d.catalog.subItems.find(candidate=>candidate.id===id)!,{description,amount:Number(amount).toFixed(2),updatedAt:new Date().toISOString()}));}else{const occurrences=promptRequired('Occorrenze',String(reusable.occurrences));const mode=promptRequired('Modalità: automatic o manual',reusable.timeMode);const manual=mode==='manual'?promptRequired('Minuti manuali per occorrenza',String(reusable.manualMinutesPerOccurrence??30)):undefined;if(!occurrences||!mode||(mode!=='automatic'&&mode!=='manual')||(mode==='manual'&&!manual))return;state.mutate(d=>{const target=d.catalog.subItems.find(candidate=>candidate.id===id);if(target?.kind==='travel')Object.assign(target,{description,occurrences:Number(occurrences),timeMode:mode,manualMinutesPerOccurrence:mode==='manual'?Number(manual):undefined,updatedAt:new Date().toISOString()});});}}
  else if(name==='edit-template'&&id){const template=doc.catalog.templates.find(candidate=>candidate.id===id);if(!template)return;const draft=structuredClone(template);const templateName=promptRequired('Nome template',draft.name);if(!templateName)return;draft.name=templateName;const itemRaw=window.prompt(`Voce da modificare (numero; vuoto modifica solo il nome template):\n${draft.items.map((item,index)=>`${index+1}. ${item.name}`).join('\n')}`,'');if(itemRaw===null)return;const item=itemRaw.trim()?draft.items[Number(itemRaw)-1]:undefined;if(itemRaw.trim()&&!item)return;if(item){const itemName=promptRequired('Nome voce',item.name);if(!itemName)return;item.name=itemName;const subRaw=window.prompt(`Sottovoce base da modificare (numero; vuoto nessuna):\n${item.subItems.map((sub,index)=>`${index+1}. ${sub.description}`).join('\n')}`,'');if(subRaw===null)return;const sub=subRaw.trim()?item.subItems[Number(subRaw)-1]:undefined;if(sub){const description=promptRequired('Descrizione sottovoce',sub.description);if(!description)return;sub.description=description;if(sub.kind==='time'){const minutes=promptRequired('Minuti',String(sub.minutes));if(!minutes)return;sub.minutes=Number(minutes);}else if(sub.kind==='expense'){const amount=promptRequired('Importo',sub.amount);if(!amount)return;sub.amount=Number(amount).toFixed(2);}}}if(!window.confirm('Salvare esplicitamente le modifiche a questo template?'))return;draft.updatedAt=new Date().toISOString();state.mutate(d=>{const index=d.catalog.templates.findIndex(candidate=>candidate.id===id);d.catalog.templates[index]=draft;});}
  else if(name==='add-preset') state.mutate(d=>d.profiles.push(createFiscalPreset2026()));
  else if(name==='add-blank-profile'){const year=Number(promptRequired('Anno del nuovo profilo',String(new Date().getFullYear())));if(!year)return;if(doc.profiles.some(p=>p.year===year)){window.alert('Esiste già un profilo per questo anno.');return;}const profile=createBlankProfile(year);activeProfileId=profile.id;state.mutate(d=>d.profiles.unshift(profile));view='dashboard';}
  else if(name==='edit-profile'&&id){activeProfileId=id;view='dashboard';render();}
  else if(name==='copy-profile'&&id){const source=doc.profiles.find(p=>p.id===id);const year=Number(promptRequired('Anno del nuovo profilo',String((source?.year??2025)+1)));if(!source||!year)return;if(doc.profiles.some(p=>p.year===year)){window.alert('Esiste già un profilo per questo anno.');return;}const copied=copyProfileToYear(source,year);if(!copied.ok){state.error=copied.error;render();return;}activeProfileId=copied.value.id;state.mutate(d=>d.profiles.unshift(copied.value));view='dashboard';}
  else if(name==='edit-local-client'&&id){const client=doc.localClients.find(c=>c.id===id);if(!client)return;const displayName=promptRequired('Denominazione',client.displayName);if(!displayName)return;const vat=window.prompt('Partita IVA facoltativa',client.vatNumber??'')??undefined;const updated=updateLocalClient(client,displayName,vat);if(!updated.ok){state.error=updated.error;render();return;}state.mutate(d=>{const index=d.localClients.findIndex(c=>c.id===id);d.localClients[index]=updated.value;for(const site of d.sites)if(site.client?.source==='local'&&site.client.localClientId===id)site.client.displayName=updated.value.displayName;});}
  else if(name==='associate-remote-site'&&id){const company=doc.settings.fic.company;if(!doc.settings.fic.enabled||!company)return;const query=promptRequired('Cerca cliente Fatture in Cloud');if(!query)return;const found=await window.cash.fic.searchClients({companyId:company.id,query});if(!found.ok){state.error=found.error;render();return;}const selected=found.value[Number(promptRequired(`Cliente:\n${found.value.map((client,index)=>`${index+1}. ${client.displayName}`).join('\n')}`))-1];if(selected)state.mutate(d=>{const site=d.sites.find(candidate=>candidate.id===id)!;site.client={source:'fatture_in_cloud',companyId:selected.companyId,clientId:selected.clientId,displayName:selected.displayName};});}
  else if(name==='clear-quote-client'){const quote=selectedQuote();if(quote)state.mutate(d=>{d.quotes.find(q=>q.id===quote.id)!.client=undefined;});}
  else if(name==='copy-remote-client'){const quote=selectedQuote();if(!quote?.client||quote.client.source!=='fatture_in_cloud')return;const homonyms=doc.localClients.filter(c=>c.displayName.localeCompare(quote.client!.displayName,'it',{sensitivity:'base'})===0);if(!window.confirm(`Creare una copia locale indipendente di “${quote.client.displayName}”?${homonyms.length?`\nAttenzione: esistono ${homonyms.length} omonimi; non verranno uniti.`:''}`))return;const created=createLocalClient(quote.client.displayName,quote.client.vatNumber);if(!created.ok){state.error=created.error;render();return;}state.mutate(d=>d.localClients.push(created.value));}
  else if(name==='new-quote') { const profile=doc.profiles.find(p=>p.confirmed); let snap; if(profile){const value=snapshotProfile(profile,doc.businessCosts);if(value.ok)snap=value.value;} const q:Quote={...meta(),date:new Date().toISOString().slice(0,10),...(profile?{profileId:profile.id}:{}),...(snap?{profileSnapshot:snap}:{}),items:[],snapshotRevision:0,exportAttempts:[]};state.mutate(d=>d.quotes.push(q));activeQuoteId=q.id; }
  else if(name==='back-quotes'){activeQuoteId=undefined;render();}
  else if(name==='add-item'){const title=promptRequired('Nome della voce commerciale');if(title){const item:QuoteItem={...meta(),name:title,subItems:[],variantGroups:[],variantSelections:[]};state.mutate(d=>d.quotes.find(q=>q.id===activeQuoteId)!.items.push(item));}}
  else if(name==='rename-item'&&id){const item=selectedQuote()?.items.find(candidate=>candidate.id===id);const title=item&&promptRequired('Nome della voce commerciale',item.name);if(item&&title)state.mutate(d=>{const target=d.quotes.find(q=>q.id===activeQuoteId)!.items.find(candidate=>candidate.id===id)!;target.name=title;target.updatedAt=new Date().toISOString();});}
  else if((name==='add-time'||name==='add-expense')&&id){const desc=promptRequired('Descrizione');const value=promptRequired(name==='add-time'?'Durata in minuti':'Importo in euro',name==='add-time'?'30':'0.00');if(desc&&value){state.mutate(d=>{const item=d.quotes.find(q=>q.id===activeQuoteId)!.items.find(i=>i.id===id)!;item.subItems.push(name==='add-time'?{...meta(),kind:'time',description:desc,minutes:Number(value)}:{...meta(),kind:'expense',description:desc,amount:Number(value).toFixed(2)});});}}
  else if(name==='add-catalog'&&id){const choices=doc.catalog.subItems.map((x,i)=>`${i+1}. ${x.description}`).join('\n');const raw=promptRequired(`Scegli il numero:\n${choices}`);const source=raw?doc.catalog.subItems[Number(raw)-1]:undefined;if(source){state.mutate(d=>{const item=d.quotes.find(q=>q.id===activeQuoteId)!.items.find(i=>i.id===id)!;if(source.kind==='time')item.subItems.push({...meta(),kind:'time',description:source.description,minutes:source.minutes});else if(source.kind==='expense')item.subItems.push({...meta(),kind:'expense',description:source.description,amount:source.amount});});}}
  else if(name==='add-travel'&&id) await addTravel(id);
  else if(name==='add-variant'&&id) await addVariant(id);
  else if(name==='save-sub'&&id){const [itemId,subId]=id.split(':');const sub=selectedQuote()?.items.find(item=>item.id===itemId)?.subItems.find(candidate=>candidate.id===subId);if(sub&&window.confirm(`Salvare “${sub.description}” come nuova copia indipendente nel catalogo?`))state.mutate(d=>d.catalog.subItems.push(reusableFromQuoteSubItem(sub)));}
  else if(name==='edit-sub'&&id){const [itemId,subId]=id.split(':');const sub=selectedQuote()?.items.find(item=>item.id===itemId)?.subItems.find(candidate=>candidate.id===subId);if(!sub)return;const description=promptRequired('Descrizione',sub.description);if(!description)return;const value=sub.kind==='time'?promptRequired('Minuti',String(sub.minutes)):sub.kind==='expense'?promptRequired('Importo',sub.amount):undefined;if((sub.kind==='time'||sub.kind==='expense')&&!value)return;state.mutate(d=>{const target=d.quotes.find(q=>q.id===activeQuoteId)!.items.find(item=>item.id===itemId)!.subItems.find(candidate=>candidate.id===subId)!;target.description=description;if(target.kind==='time')target.minutes=Number(value);else if(target.kind==='expense')target.amount=Number(value).toFixed(2);if(target.variantOwner)target.manuallyModified=true;target.updatedAt=new Date().toISOString();});}
  else if(name==='insert-template') await insertTemplate();
  else if(name==='save-template') saveTemplate();
  else if(name==='refresh-quote') await performRefresh();
  else if(name==='export-quote') await performExport();
  else if(name==='activate-fic') await activateFic();
  else if(name==='disable-fic') state.mutate(d=>{d.settings.fic.enabled=false;});
  else if(name==='remove-fic') {if(!window.confirm('Rimuovere configurazione condivisa e token locale? Gli snapshot storici resteranno invariati.'))return;await state.save();if(state.status!=='Salvato'||!state.session?.document)return;const removed=await window.cash.fic.removeLink({path:state.session.path,document:state.session.document,concurrencyToken:state.session.token});if(!removed.ok){state.error=removed.error;render();return;}hasFicToken=false;state.acceptNativeSession(removed.value);}
}

async function activateFic():Promise<void>{
  if(!ficSetupInfo.clientId){window.alert('Questa build non contiene il Client ID dell’app privata. Ricompilarla impostando CASH_FIC_CLIENT_ID.');return;}
  await state.save();if(state.status!=='Salvato'||!state.session?.document)return;
  const token=promptRequired('Incolla il token manuale. Client ID e permessi richiesti sono indicati nelle istruzioni della scheda.');if(!token)return;
  const companies=await window.cash.fic.listCompaniesForActivation(token);if(!companies.ok){ficConnectionError=true;state.error=companies.error;render();return;}
  const companyIndex=Number(promptRequired(`Seleziona azienda:\n${companies.value.map((c,i)=>`${i+1}. ${c.name}`).join('\n')}`))-1;
  const company=companies.value[companyIndex];if(!company)return;
  const products=await window.cash.fic.listProductsForActivation({token,companyId:company.id});if(!products.ok){ficConnectionError=true;state.error=products.error;render();return;}
  if(!products.value.length){window.alert('Nessun prodotto con nome esatto “Consulenza”. Crearlo in Fatture in Cloud e riprovare.');return;}
  const productIndex=products.value.length===1?0:Number(promptRequired(`Seleziona prodotto Consulenza:\n${products.value.map((p,i)=>`${i+1}. ${p.name} (${p.id})`).join('\n')}`))-1;
  const product=products.value[productIndex];if(!product)return;
  const completed=await window.cash.fic.completeActivation({token,companyId:company.id,productId:product.id,path:state.session.path,document:state.session.document,concurrencyToken:state.session.token});if(!completed.ok){ficConnectionError=true;state.error=completed.error;render();return;}
  hasFicToken=true;ficConnectionError=false;state.acceptNativeSession(completed.value);
}

async function addTravel(itemId:string):Promise<void>{
  const doc=documentNow()!, quote=selectedQuote()!, profile=profileFor(quote);
  if(!doc.settings.fuelTerritory){window.alert('Configura prima la regione MIMIT.');return;} if(!doc.sites.length||!doc.vehicles.length){window.alert('Configura almeno una Sede e un veicolo.');return;}
  const proposed=Math.max(0,doc.sites.findIndex(site=>site.id===quote.mainSite?.sourceId))+1;const site=doc.sites[Number(promptRequired(`Sede:\n${doc.sites.map((x,i)=>`${i+1}. ${x.name}`).join('\n')}`,String(proposed)))-1]; const vehicle=doc.vehicles[Number(promptRequired(`Veicolo:\n${doc.vehicles.map((x,i)=>`${i+1}. ${x.name}`).join('\n')}`,'1'))-1];
  if(!site||!vehicle)return; const description=promptRequired('Descrizione trasferta',`Trasferta ${site.name}`);if(!description)return;
  const occurrences=Number(promptRequired('Occorrenze previste','1')); const roundTrip=window.confirm('Andata e ritorno?'); const manual=promptRequired('Minuti manuali per occorrenza (lascia vuoto per automatico)','');
  const fuel=await window.cash.mimit.latestFuelPrice({territory:doc.settings.fuelTerritory,fuel:vehicle.fuel});if(!fuel.ok){state.error=fuel.error;render();return;}const cost=calculateVehicleCost(vehicle,fuel.value);if(!cost.ok){state.error=cost.error;render();return;}
  const travel=calculateTravel({oneWayKm:site.oneWayKm,roundTrip,occurrences,vehicleCostPerKm:cost.value.costPerKm,...(manual?{manualMinutesPerOccurrence:Number(manual)}:{speedKmh:profile?.capacity.travelSpeedKmh})});if(!travel.ok){state.error=travel.error;render();return;}
  state.mutate(d=>d.quotes.find(q=>q.id===quote.id)!.items.find(i=>i.id===itemId)!.subItems.push({...meta(),kind:'travel',description,site:{sourceId:site.id,name:site.name,address:site.address,...(site.oneWayKm!==undefined?{oneWayKm:site.oneWayKm}:{})},vehicleId:vehicle.id,roundTrip,occurrences,timeMode:manual?'manual':'automatic',...(manual?{manualMinutesPerOccurrence:Number(manual)}:{}),...travel.value,vehicleCostPerKm:cost.value.costPerKm,fuelEvidence:fuel.value}));
}

async function addVariant(itemId:string):Promise<void>{
  const quote=selectedQuote();const source=quote?.items.find(item=>item.id===itemId);if(!quote||!source)return;
  const name=promptRequired('Nome gruppo variante');const names=promptRequired('Nomi delle opzioni, uno per riga','Nessuna\nStandard');if(!name||!names)return;
  const options=[];
  for(const optionName of names.split(/\r?\n/).map(value=>value.trim()).filter(Boolean)){
    const raw=window.prompt(`Sottovoci prodotte da “${optionName}”, una per riga.\nFormati:\ntempo|Descrizione|minuti\nspesa|Descrizione|euro\ntrasferta|Descrizione|AR o A|occorrenze|automatic o manual|minuti manuali`,optionName==='Nessuna'?'':`tempo|${name} · ${optionName}|30`);if(raw===null)return;
    const definitions:SubItemDefinition[]=[];
    for(const line of raw.split(/\r?\n/).map(value=>value.trim()).filter(Boolean)){
      const [kind,description,value,occurrences,timeMode,manualMinutes]=line.split('|').map(value=>value?.trim());
      if(!description){window.alert(`Definizione non valida: ${line}`);return;}
      if(kind==='tempo'&&Number.isInteger(Number(value))&&Number(value)>0)definitions.push({kind:'time',description,minutes:Number(value)});
      else if(kind==='spesa'&&Number(value)>=0)definitions.push({kind:'expense',description,amount:Number(value).toFixed(2)});
      else if(kind==='trasferta'&&Number.isInteger(Number(occurrences))&&Number(occurrences)>0&&(timeMode==='automatic'||timeMode==='manual'))definitions.push({kind:'travel',description,roundTrip:value?.toLocaleUpperCase('it')==='AR',occurrences:Number(occurrences),timeMode,...(timeMode==='manual'&&Number(manualMinutes)>0?{manualMinutesPerOccurrence:Number(manualMinutes)}:{})});
      else{window.alert(`Definizione non valida: ${line}`);return;}
    }
    options.push({...meta(),name:optionName,subItems:definitions});
  }
  const defaultRaw=window.prompt(`Opzione predefinita (numero, lascia vuoto per nessun default):\n${options.map((option,index)=>`${index+1}. ${option.name}`).join('\n')}`,'1');if(defaultRaw===null)return;
  const defaultOption=defaultRaw.trim()?options[Number(defaultRaw)-1]:undefined;if(defaultRaw.trim()&&!defaultOption){window.alert('Opzione predefinita non valida.');return;}
  const group={...meta(),name,options,...(defaultOption?{defaultOptionId:defaultOption.id}:{})};const validation=validateVariantGroups([...source.variantGroups,group]);if(!validation.ok){state.error=validation.error;render();return;}
  let selected=defaultOption;if(!selected){const selectedRaw=promptRequired(`Questo gruppo non ha default: scegli esplicitamente l’opzione iniziale.\n${options.map((option,index)=>`${index+1}. ${option.name}`).join('\n')}`);selected=selectedRaw?options[Number(selectedRaw)-1]:undefined;if(!selected)return;}
  const travelQueue:QuoteSubItem[]=[];for(const definition of selected.subItems)if(definition.kind==='travel'){const travel=await materializeTemplateTravel(definition,quote);if(!travel)return;travelQueue.push(travel);}
  const draft=structuredClone(source);draft.variantGroups.push(group);const applied=changeVariant(draft,group.id,selected.id,true,{materializeTravel:()=>{const travel=travelQueue.shift();return travel?{ok:true,value:travel}:{ok:false,error:{code:'MISSING_DATA',message:'Dati Trasferta non disponibili.'}};}});
  if(!applied.ok){state.error=applied.error;render();return;}state.mutate(d=>Object.assign(d.quotes.find(q=>q.id===quote.id)!.items.find(item=>item.id===itemId)!,applied.value));
}

function saveTemplate():void{const quote=selectedQuote();const name=promptRequired('Nome del nuovo template');if(!quote||!name)return;const raw=promptRequired(`Voci da includere (numeri separati da virgola):\n${quote.items.map((item,index)=>`${index+1}. ${item.name}`).join('\n')}`,quote.items.map((_item,index)=>index+1).join(','));if(!raw)return;const items=[...new Set(raw.split(',').map(value=>quote.items[Number(value.trim())-1]).filter((item):item is QuoteItem=>Boolean(item)))];const built=templateFromQuote(name,items);if(!built.ok){state.error=built.error;render();return;}const preview=previewTemplate(name,items);const changed=items.flatMap(item=>item.subItems.filter(sub=>sub.variantOwner&&sub.manuallyModified).map(sub=>`${item.name} / ${sub.description}`));if(!window.confirm(`Anteprima del nuovo template (sempre una copia):\n${preview.items.map(item=>`${item.name}: ${item.subItems.join(', ')||'nessuna sottovoce base'}${item.variants.length?` · varianti ${item.variants.map(v=>v.group).join(', ')}`:''}`).join('\n')}${changed.length?`\n\nLe modifiche manuali seguenti saranno applicate alle rispettive opzioni:\n${changed.join('\n')}`:''}\n\nSalvare?`))return;state.mutate(d=>d.catalog.templates.push(built.value));}

async function performRefresh():Promise<void>{const doc=documentNow()!,quote=selectedQuote();if(!quote)return;const result=await refreshQuote(quote,{profileById:id=>doc.profiles.find(x=>x.id===id),costs:doc.businessCosts,siteById:id=>doc.sites.find(x=>x.id===id),vehicleById:id=>doc.vehicles.find(x=>x.id===id),fuel:vehicle=>doc.settings.fuelTerritory?window.cash.mimit.latestFuelPrice({territory:doc.settings.fuelTerritory,fuel:vehicle.fuel}):Promise.resolve({ok:false,error:{code:'MISSING_DATA',field:'fuelTerritory',message:'Regione MIMIT non configurata.'}}),foi:(amount,period)=>window.cash.istat.revalue({amount,fromPeriod:period})});if(!result.ok){state.error=result.error;render();return;}state.mutate(d=>{const index=d.quotes.findIndex(x=>x.id===quote.id);d.quotes[index]=result.value;});}

async function performExport():Promise<void>{
  const doc=documentNow()!,quote=selectedQuote(),fic=doc.settings.fic;if(!quote)return;
  if(!fic.enabled||!fic.company||!fic.product){window.alert('Fatture in Cloud è disattivato o non configurato. Il preventivo resta utilizzabile localmente.');return;}
  let remoteClient=quote.client;
  if(!remoteClient||remoteClient.source!=='fatture_in_cloud'||remoteClient.companyId!==fic.company.id){
    const query=promptRequired('Cerca e seleziona esplicitamente il cliente remoto per questa esportazione',quote.client?.displayName??'');if(!query)return;
    const found=await window.cash.fic.searchClients({companyId:fic.company.id,query});if(!found.ok){state.error=found.error;render();return;}
    const selected=found.value[Number(promptRequired(`Cliente remoto:\n${found.value.map((c,i)=>`${i+1}. ${c.displayName} · ${c.vatNumber??'P.IVA assente'}`).join('\n')}`))-1];if(!selected)return;
    if(!window.confirm(`Sostituire lo snapshot cliente del preventivo con “${selected.displayName}”? Il Cliente locale originario non verrà modificato.`))return;
    remoteClient=selected;state.mutate(d=>{d.quotes.find(q=>q.id===quote.id)!.client=selected;});await state.save();if(state.status!=='Salvato')return;
  }
  const exportQuoteSnapshot={...quote,client:remoteClient};
  if(needsRepeatWarning(exportQuoteSnapshot)&&!window.confirm('Preventivo già esportato o con esito da verificare. Confermi una nuova esportazione?'))return;
  const product=await window.cash.fic.verifyProduct({companyId:fic.company.id,productId:fic.product.id});if(!product.ok){state.error=product.error;render();return;}
  let groups:Array<{itemIds:string[];description:string}>|undefined;
  if(quote.items.length>1&&window.confirm('Raggruppare tutte le voci in una sola riga di esportazione?')){
    const description=promptRequired('Descrizione modificabile della riga',quote.items.map(item=>item.name).join(' + '));if(!description)return;groups=[{itemIds:quote.items.map(item=>item.id),description}];
  } else {
    groups=[];for(const item of quote.items){const description=promptRequired(`Descrizione riga per “${item.name}”`,item.name);if(!description)return;groups.push({itemIds:[item.id],description});}
  }
  const built=buildExportLines(exportQuoteSnapshot,groups,fic.company.id);if(!built.ok){state.error=built.error;render();return;}
  if(!window.confirm(`Anteprima definitiva:\n${built.value.map(line=>`${line.description}: ${eur(line.amount)} · quantità 1`).join('\n')}\n\nInviare?`))return;
  const attempt=createPendingAttempt(fic.company.id,built.value);state.mutate(d=>d.quotes.find(q=>q.id===quote.id)!.exportAttempts.push(attempt));await state.save();if(state.status!=='Salvato')return;
  const sent=await window.cash.fic.exportQuote({companyId:fic.company.id,clientId:remoteClient.clientId,productId:fic.product.id,lines:built.value,attemptId:attempt.id});
  state.mutate(d=>{const saved=d.quotes.find(q=>q.id===quote.id)!.exportAttempts.find(x=>x.id===attempt.id)!;if(sent.ok){saved.outcome=sent.value.outcome;if(sent.value.remoteDocumentId)saved.remoteDocumentId=sent.value.remoteDocumentId;if(sent.value.diagnostic)saved.diagnostic=sent.value.diagnostic;}else{saved.outcome='uncertain';saved.diagnostic=sent.error.message;}});
}

root.addEventListener('click',event=>{const target=(event.target as HTMLElement).closest<HTMLElement>('[data-view],[data-action],[data-open-quote],[data-delete]');if(!target)return;if(target.dataset.view){view=target.dataset.view as View;activeQuoteId=undefined;render();}else if(target.dataset.openQuote){activeQuoteId=target.dataset.openQuote;view='quotes';render();}else if(target.dataset.delete){const [kind,...parts]=target.dataset.delete.split(':');const id=parts.join(':');if(kind&&id&&window.confirm('Eliminare questo elemento?'))mutateEntityList(kind,id);}else if(target.dataset.action)void action(target.dataset.action,target.dataset.id);});

root.addEventListener('change',event=>{const target=event.target as HTMLSelectElement;if(target.dataset.variant)void changeVariantFromUi(target.dataset.variant,target.value);});

root.addEventListener('submit',event=>{event.preventDefault();const form=event.target as HTMLFormElement;const data=new FormData(form);const get=(name:string)=>String(data.get(name)??'').trim();const doc=documentNow();if(!doc)return;const kind=form.dataset.form;
  if(kind==='profile'){const previous=doc.profiles.find(profile=>profile.id===activeProfileId)??doc.profiles[0]!;const draft=structuredClone(previous);draft.year=Number(get('year'));if(doc.profiles.some(profile=>profile.id!==previous.id&&profile.year===draft.year)){window.alert('Esiste già un profilo per questo anno.');return;}draft.revenueTarget=get('revenueTarget');draft.specificAnnualExpenses=get('specificAnnualExpenses');draft.capacity.hoursPerDay=get('hoursPerDay');draft.capacity.clientTimePercentage=get('clientTimePercentage');draft.capacity.vacationDays=Number(get('vacationDays'));draft.capacity.unplannedDays=Number(get('unplannedDays'));draft.capacity.travelSpeedKmh=get('travelSpeedKmh')||undefined;draft.capacity.localHolidays=parseLocalHolidays(get('localHolidays'));draft.fiscal={...draft.fiscal,atecoCode:get('atecoCode'),profitabilityCoefficient:get('profitabilityCoefficient'),contributionRate:get('contributionRate'),contributionCeiling:get('contributionCeiling'),activityPhase:get('activityPhase') as EconomicProfile['fiscal']['activityPhase'],reducedEligibilityConfirmed:data.get('reducedEligibilityConfirmed')==='on',ordinaryApplicabilityConfirmed:data.get('ordinaryApplicabilityConfirmed')==='on',reducedSubstituteTaxRate:get('reducedSubstituteTaxRate'),ordinarySubstituteTaxRate:get('ordinarySubstituteTaxRate'),ordinaryThreshold:get('ordinaryThreshold'),cessationThreshold:get('cessationThreshold')};let saved=saveProfileRevision(previous,draft);const profileAction=((event as SubmitEvent).submitter as HTMLButtonElement|null)?.value;if(profileAction==='confirm'){const confirmed=confirmProfile(saved,doc.businessCosts);if(!confirmed.ok){state.error=confirmed.error;render();return;}saved=confirmed.value;}state.mutate(d=>{const index=d.profiles.findIndex(p=>p.id===previous.id);d.profiles[index]=saved;});}
  else if(kind==='local-client'){const created=createLocalClient(get('displayName'),get('vatNumber'));if(!created.ok){state.error=created.error;render();return;}state.mutate(d=>d.localClients.push(created.value));}
  else if(kind==='client-filter'){const container=document.querySelector('#local-client-list');if(container){const matches=searchLocalClients(doc.localClients,get('query'));container.innerHTML=matches.map(client=>`<div class="row"><div><strong>${esc(client.displayName)}</strong><div class="row-detail">${esc(client.vatNumber??'P.IVA non indicata')}</div></div><div class="row-actions"><button class="secondary" data-action="edit-local-client" data-id="${client.id}">Modifica</button><button class="danger" data-delete="local-client:${client.id}">Elimina</button></div></div>`).join('')||'<div class="empty">Nessun risultato.</div>';}}
  else if(kind==='cost')state.mutate(d=>d.businessCosts.push({...meta(),category:get('category'),description:get('description'),monthlyAmount:Number(get('monthlyAmount')).toFixed(2)}));
  else if(kind==='vehicle')state.mutate(d=>d.vehicles.push({...meta(),name:get('name'),fuel:get('fuel') as Vehicle['fuel'],consumption:get('consumption'),consumptionUnit:get('fuel')==='Metano'?'kg/100km':'l/100km',annualKm:get('annualKm'),annualInsurance:Number(get('annualInsurance')).toFixed(2),annualTax:Number(get('annualTax')).toFixed(2),annualMaintenance:Number(get('annualMaintenance')).toFixed(2)}));
  else if(kind==='site'){const client=doc.localClients.find(c=>c.id===get('localClientId'));state.mutate(d=>d.sites.push({...meta(),name:get('name'),address:get('address'),...(client?{client:{source:'local',localClientId:client.id,displayName:client.displayName} as const}:{}),...(get('oneWayKm')?{oneWayKm:Number(get('oneWayKm')).toFixed(1)}:{})}));}
  else if(kind==='catalog')state.mutate(d=>{if(get('kind')==='time')d.catalog.subItems.push({...meta(),kind:'time',description:get('description'),minutes:Number(get('value'))});else if(get('kind')==='expense')d.catalog.subItems.push({...meta(),kind:'expense',description:get('description'),amount:Number(get('value')).toFixed(2)});else d.catalog.subItems.push({...meta(),kind:'travel',description:get('description'),roundTrip:data.get('roundTrip')==='on',occurrences:Number(get('occurrences')),timeMode:get('timeMode') as 'automatic'|'manual',...(get('timeMode')==='manual'?{manualMinutesPerOccurrence:Number(get('value'))}:{})});});
  else if(kind==='settings')state.mutate(d=>{d.settings={...(get('fuelTerritory')?{fuelTerritory:get('fuelTerritory')}:{}),fic:d.settings.fic};});
  else if(kind==='quote'){const quote=selectedQuote()!;const profile=doc.profiles.find(p=>p.id===get('profileId'));const quoteYear=Number(get('date').slice(0,4));if(profile&&profile.year!==quoteYear&&!window.confirm(`La data è nel ${quoteYear}, ma il profilo selezionato è ${profile.year}. Mantenere questa associazione esplicita?`))return;const snap=profile?snapshotProfile(profile,doc.businessCosts):undefined;if(profile&&!snap?.ok){state.error=snap?.error??{code:'MISSING_DATA',message:'Profilo non calcolabile.'};render();return;}state.mutate(d=>{const q=d.quotes.find(x=>x.id===quote.id)!;q.date=get('date');q.commission=get('commission')?Number(get('commission')).toFixed(2):undefined;q.profileId=profile?.id;q.profileSnapshot=snap?.ok?snap.value:undefined;q.mainSite=get('mainSiteId')?siteSnapshot(get('mainSiteId')):undefined;});}
  else if(kind==='item-price'){const quote=selectedQuote()!;state.mutate(d=>{const item=d.quotes.find(q=>q.id===quote.id)!.items.find(i=>i.id===form.dataset.id)!;item.chosenPrice=get('chosenPrice')?Number(get('chosenPrice')).toFixed(2):undefined;item.referencePrice=get('referenceAmount')&&get('referencePeriod')?{amount:Number(get('referenceAmount')).toFixed(2),period:get('referencePeriod')}:undefined;});}
  else if(kind==='quote-local-client'){const client=doc.localClients.find(c=>c.id===get('localClientId'));if(client)state.mutate(d=>{d.quotes.find(q=>q.id===activeQuoteId)!.client=snapshotLocalClient(client);});}
  else if(kind==='client-search'){const companyId=doc.settings.fic.company?.id;if(!doc.settings.fic.enabled||!companyId){window.alert('Attivare prima Fatture in Cloud.');return;}void window.cash.fic.searchClients({companyId,query:get('query')}).then(result=>{if(!result.ok){state.error=result.error;render();return;}const container=document.querySelector('#client-results')!;container.innerHTML=result.value.map(c=>`<button class="secondary" data-client="${encodeURIComponent(JSON.stringify(c))}">${esc(c.displayName)} · ${esc(c.vatNumber??'P.IVA assente')}</button>`).join(' ');container.querySelectorAll<HTMLButtonElement>('[data-client]').forEach(button=>button.onclick=()=>{const client=JSON.parse(decodeURIComponent(button.dataset.client!));state.mutate(d=>{d.quotes.find(q=>q.id===activeQuoteId)!.client=client;});});});}
});

async function materializeTemplateTravel(definition:Extract<SubItemDefinition,{kind:'travel'}>,quote:Quote):Promise<QuoteSubItem|undefined>{
  const doc=documentNow()!,profile=profileFor(quote);if(!doc.settings.fuelTerritory||!doc.sites.length||!doc.vehicles.length){window.alert('Per inserire una Trasferta servono territorio MIMIT, Sede e veicolo.');return undefined;}
  const proposed=Math.max(0,doc.sites.findIndex(site=>site.id===quote.mainSite?.sourceId))+1;
  const site=doc.sites[Number(promptRequired(`Sede per “${definition.description}”:\n${doc.sites.map((candidate,index)=>`${index+1}. ${candidate.name}`).join('\n')}`,String(proposed)))-1];
  const vehicle=doc.vehicles[Number(promptRequired(`Veicolo per “${definition.description}”:\n${doc.vehicles.map((candidate,index)=>`${index+1}. ${candidate.name}`).join('\n')}`,'1'))-1];if(!site||!vehicle)return undefined;
  const fuel=await window.cash.mimit.latestFuelPrice({territory:doc.settings.fuelTerritory,fuel:vehicle.fuel});if(!fuel.ok){state.error=fuel.error;render();return undefined;}const cost=calculateVehicleCost(vehicle,fuel.value);if(!cost.ok){state.error=cost.error;render();return undefined;}
  const travel=calculateTravel({oneWayKm:site.oneWayKm,roundTrip:definition.roundTrip,occurrences:definition.occurrences,vehicleCostPerKm:cost.value.costPerKm,...(definition.timeMode==='manual'?{manualMinutesPerOccurrence:definition.manualMinutesPerOccurrence}:{speedKmh:profile?.capacity.travelSpeedKmh})});if(!travel.ok){state.error=travel.error;render();return undefined;}
  return {...meta(),kind:'travel',description:definition.description,site:{sourceId:site.id,name:site.name,address:site.address,...(site.oneWayKm!==undefined?{oneWayKm:site.oneWayKm}:{})},vehicleId:vehicle.id,roundTrip:definition.roundTrip,occurrences:definition.occurrences,timeMode:definition.timeMode,...(definition.manualMinutesPerOccurrence?{manualMinutesPerOccurrence:definition.manualMinutesPerOccurrence}:{}),...travel.value,vehicleCostPerKm:cost.value.costPerKm,fuelEvidence:fuel.value};
}

async function changeVariantFromUi(key:string,optionId:string):Promise<void>{
  const [itemId,groupId]=key.split(':');const quote=selectedQuote();const item=quote?.items.find(candidate=>candidate.id===itemId);const group=item?.variantGroups.find(candidate=>candidate.id===groupId);const option=group?.options.find(candidate=>candidate.id===optionId);if(!quote||!item||!group||!option)return;
  const warning=item.subItems.some(sub=>sub.variantOwner?.groupId===group.id&&sub.manuallyModified);if(warning&&!window.confirm('Le modifiche manuali alle sottovoci della variante verranno perse. Continuare?')){render();return;}
  const travelQueue:QuoteSubItem[]=[];for(const definition of option.subItems)if(definition.kind==='travel'){const travel=await materializeTemplateTravel(definition,quote);if(!travel){render();return;}travelQueue.push(travel);}
  const changed=changeVariant(item,group.id,option.id,true,{materializeTravel:()=>{const travel=travelQueue.shift();return travel?{ok:true,value:travel}:{ok:false,error:{code:'MISSING_DATA',message:'Dati Trasferta non disponibili.'}};}});
  if(!changed.ok){state.error=changed.error;render();return;}state.mutate(d=>Object.assign(d.quotes.find(candidate=>candidate.id===quote.id)!.items.find(candidate=>candidate.id===item.id)!,changed.value));
}

async function insertTemplate():Promise<void>{
  const doc=documentNow()!,quote=selectedQuote();if(!quote)return;const selected=doc.catalog.templates[Number(promptRequired(`Template:\n${doc.catalog.templates.map((template,index)=>`${index+1}. ${template.name}`).join('\n')}`))-1];if(!selected)return;const template=cloneTemplate(selected);const prepared:QuoteItem[]=[];
  for(const source of template.items){const item:QuoteItem={...meta(),name:source.name,subItems:[],variantGroups:source.variantGroups,variantSelections:[],...(source.referencePrice?{referencePrice:{...source.referencePrice}}:{})};
    for(const reusable of source.subItems){if(reusable.kind==='time')item.subItems.push({...meta(),kind:'time',description:reusable.description,minutes:reusable.minutes});else if(reusable.kind==='expense')item.subItems.push({...meta(),kind:'expense',description:reusable.description,amount:reusable.amount});else{const travel=await materializeTemplateTravel(reusable,quote);if(!travel)return;item.subItems.push(travel);}}
    const choices:Record<string,string>={};const travelQueue:QuoteSubItem[]=[];
    for(const group of item.variantGroups){let optionId=group.defaultOptionId;if(!optionId){const option=group.options[Number(promptRequired(`Opzione per ${group.name}:\n${group.options.map((candidate,index)=>`${index+1}. ${candidate.name}`).join('\n')}`))-1];if(!option)return;optionId=option.id;}choices[group.id]=optionId;const option=group.options.find(candidate=>candidate.id===optionId)!;for(const definition of option.subItems)if(definition.kind==='travel'){const travel=await materializeTemplateTravel(definition,quote);if(!travel)return;travelQueue.push(travel);}}
    const applied=applyVariantSelections(item,choices,{materializeTravel:()=>{const travel=travelQueue.shift();return travel?{ok:true,value:travel}:{ok:false,error:{code:'MISSING_DATA',message:'Dati Trasferta non disponibili.'}};}});if(!applied.ok){state.error=applied.error;render();return;}prepared.push(applied.value);
  }
  if(window.confirm(`Inserire una copia indipendente del template “${selected.name}” con ${prepared.length} voci?`))state.mutate(d=>d.quotes.find(candidate=>candidate.id===quote.id)!.items.push(...prepared));
}

root.addEventListener('input',event=>{
  const form=(event.target as HTMLElement).closest<HTMLFormElement>('form[data-form="profile"]');const doc=documentNow();if(!form||!doc)return;
  const source=doc.profiles.find(profile=>profile.id===activeProfileId)??doc.profiles[0];if(!source)return;const data=new FormData(form);const get=(name:string)=>String(data.get(name)??'').trim();
  const draft=structuredClone(source);draft.year=Number(get('year'));draft.revenueTarget=get('revenueTarget');draft.specificAnnualExpenses=get('specificAnnualExpenses');draft.capacity={...draft.capacity,hoursPerDay:get('hoursPerDay'),clientTimePercentage:get('clientTimePercentage'),vacationDays:Number(get('vacationDays')),unplannedDays:Number(get('unplannedDays')),travelSpeedKmh:get('travelSpeedKmh')||undefined,localHolidays:parseLocalHolidays(get('localHolidays'))};draft.fiscal={...draft.fiscal,atecoCode:get('atecoCode'),profitabilityCoefficient:get('profitabilityCoefficient'),contributionRate:get('contributionRate'),contributionCeiling:get('contributionCeiling'),activityPhase:get('activityPhase') as EconomicProfile['fiscal']['activityPhase'],reducedEligibilityConfirmed:data.get('reducedEligibilityConfirmed')==='on',ordinaryApplicabilityConfirmed:data.get('ordinaryApplicabilityConfirmed')==='on',reducedSubstituteTaxRate:get('reducedSubstituteTaxRate'),ordinarySubstituteTaxRate:get('ordinarySubstituteTaxRate'),ordinaryThreshold:get('ordinaryThreshold'),cessationThreshold:get('cessationThreshold')};
  const preview=previewProfile(draft,doc.businessCosts);const target=document.querySelector('#profile-preview');if(target)target.innerHTML=preview.ok?`Anteprima: aliquota effettiva <strong>${esc(preview.value.effectiveTaxRate??'—')}%</strong> · reddito forfettario ${eur(preview.value.forfaitIncome)} · base contributiva ${eur(preview.value.contributionBase)} · contributi ${eur(preview.value.contributions)} · base imposta ${eur(preview.value.taxBase)} · imposta ${eur(preview.value.substituteTax)}`:`Anteprima non disponibile: ${esc(preview.error.message)}`;
});

state.subscribe(render);
render();
void state.initialize();
void window.cash.credentials.hasFicToken().then(result=>{hasFicToken=result.ok&&result.value;ficConnectionError=!result.ok;render();});
void window.cash.fic.setupInfo().then(info=>{ficSetupInfo=info;render();});
window.cash.onCloseRequested(()=>{void (async()=>{const choice=window.prompt('Modifiche non salvate. Digita: salva, recupero, scarta oppure annulla.','annulla')?.trim().toLocaleLowerCase('it');if(choice==='salva'){await state.save();window.cash.resolveClose(state.status==='Salvato'?'discard':'cancel');}else if(choice==='recupero'){window.cash.resolveClose(await state.recovery()?'discard':'cancel');}else if(choice==='scarta'){window.cash.resolveClose('discard');}else window.cash.resolveClose('cancel');})();});
